### ISSUE TITLE
Immediately unlock Aegis after entering numerical password with enabled PIN keyboard without tapping "Unlock" button after

### ISSUE THREAD

**Issue by CfYz-R** [beemdevelopment/Aegis#1029]
So the title says for itself. Option for this will be very useful!

But maybe this will be good for chars passwords too? :)

**Comment by loyl1** [comment]
I wouldn't want this as a default. It weakens security making it easier for an adversary to unlock the database. Having to guess the password length is much better security

**Comment by alexbakker** [comment]
This feature is not a great fit for Aegis.

The app doesn't store the password and thus also doesn't know its length. So, it would have to attempt to decrypt the vault after every new character of the password that you enter. Attempting to decrypt the vault is deliberately computationally expensive, because we use scrypt to derive a key from the user's password. Each attempt can take up to a couple of seconds depending on the device. The implementation of scrypt that we use doesn't have an option to cancel the operation once you start it, so if your password is 15 characters and each attempt takes 1 second to complete for example, you'd potentially be sitting there waiting 15 seconds for all of the decryption attempts to complete.
