### ISSUE TITLE
Unable to import from FreeOTP tokens.xml

### ISSUE THREAD

**Issue by Fibroblasto** [beemdevelopment/Aegis#1031]
### Version

2.1

### Source

Google Play

### Vault encryption

Yes (with biometric unlock)

### Device

LeEco cool1 dual

### Android version

6.0.1

### Steps to reproduce

Settings > Import & Export > Import from file > select FreeOTP

Selecting tokens.xml I get this error:

`java.io.FileNotFoundException: /storage/emulated/0/Download/tokens.xml: open failed: EACCES (Permission denied)`

The file can be read without problems by other programs.

### What do you expect to happen?

It should be able to import from FreeOTP

### What happens instead?

Data is not imported from FreeOTP.

### Log

[debug.log](https://github.com/beemdevelopment/Aegis/files/10059799/debug.log)

**Comment by alexbakker** [comment]
@Fibroblasto @Quintus19 Thank you both for the report. This is a little odd, it's almost as if on your devices, SAF is giving back a ``file://`` URI in response to you selecting a file to import, instead of a ``content://`` URI. Could you both try again with [this debug APK](https://alexbakker.me/u/jzrwkgmfmc.apk) and report back with the error message again? It may also be helpful to have a screen recording of you reproducing the issue.

**Comment by Quintus19** [comment]
Unfortunately it did not work. But it gave a different error message this time.
![aegisdev_newerror](https://user-images.githubusercontent.com/119014876/204356054-8211b51f-2333-4bae-a12d-5b91a0c2f18d.jpg)


Also, here is the recording you requested:


https://user-images.githubusercontent.com/119014876/204357945-68517830-b5bf-4dd3-a8d3-84800ef8586f.mp4




Out of curiosity, does this have anything to do with our Android version? We are both on Android 6.

**Comment by alexbakker** [comment]
Thanks! That screen recording clears things up. This is likely happening because you're tapping "File Manager", which is presumably some third party app. Please try selecting the file directly from one of the options here (Enable "Show internal storage" or similar if needed):

![image](https://user-images.githubusercontent.com/2387841/204362964-85acad2e-d0fb-4ec4-a3c9-9b1e14113ca9.png)

**Comment by Quintus19** [comment]
Thank you it worked!
The option to view internal storage was not there before so I could not directly do it from that prompt. Now it's here for some reason. The "file manager" is phone's stock manager so I used that and other third parties.

It was confusing since I could not access the internal storage before.
Anyway I suppose it was a problem on my end. It worked for both debug and stable apks.
Keep up the good work!

**Comment by 3xploiton3** [comment]
> Thanks! That error message and screen recording clears things up. As expected, the URI returned after file selection starts with `file:///`. This is likely happening because you're tapping "File Manager", which is presumably some third party app. Please try selecting the file directly from one of the options here (Enable "Show internal storage" or similar if needed):
> 
> ![image](https://user-images.githubusercontent.com/2387841/204362964-85acad2e-d0fb-4ec4-a3c9-9b1e14113ca9.png)

thanks that method it worked

**Comment by andreymal** [comment]
> Please try selecting the file directly from one of the options here

My phone (Xiaomi Redmi 4X) doesn't have such options.

In fact, I had to install a third-party app (Total Commander) to make this work
