### ISSUE TITLE
Give import hint on export QR screen

### ISSUE THREAD

**Issue by jidanni** [beemdevelopment/Aegis#1051]
Here the user has figured out how to export a single entry via QR code:
<img src="https://user-images.githubusercontent.com/1230959/205465864-e3ac8c17-dde2-4f69-8707-3f1e81666e50.jpg" width="400"/>
The problem is how to import it into another a second cellphone also running the same Aegis app.

So he's on the other cell phone and  he digs into Settings and does find that import export thing but sorry, it's a dead end. Nothing about QR codes there

So on the above image there should be in small print something mentioning that all he really needs to do, if he happens to be trying to import it into another Aegis, is simply hit the big red plus button on the front of that app.

**Comment by jidanni** [comment]
So maybe all you need is just one extra Unicode character:

"Scan this QR..." should be:

"Scan [picture of a red circle with a plus in it] this QR..."

**Comment by alexbakker** [comment]
I don't think we should change anything here. The message displayed should apply to all 2FA apps, not just Aegis, and it already clearly says that they should scan the QR code. Users of Aegis already know how to do that, because when you start out with an empty entry list, there's a message telling you to tap the FAB.

**Comment by jidanni** [comment]
( Ah, but that's years ago when we saw that message. How about something deep in the export import menu that just tells people that are trying to import in this case that they should just tap the big red button.)
