### ISSUE TITLE
[Feature Request] Copy on first tap when using tap to reveal

### ISSUE THREAD

**Issue by D3SOX** [beemdevelopment/Aegis#1064]
I would like a feature where it already copies the token to the clipboard on the same tap when using the "Tap to reveal" and "Copy tokens when tapped" option.
My use case is that I always copy tokens from mobile and KDE Connect syncs my clipboard, and then I can paste it directly on my desktop.

**Comment by alexbakker** [comment]
> I would like a feature where it already copies the token to the clipboard on the same tap when using the "Tap to reveal" and "Copy tokens when tapped" option

This used to be the way things worked, but the behavior was changed recently so that copying requires a second tap if you combine "Tap to reveal" and "Copy token when tapped". See #690 for the rationale.

Rather than introducing yet another customization option, I'm tempted to say: Just double tap, that'll essentially get you the old behavior.

**Comment by D3SOX** [comment]
Ah, that explains it because I thought that the behavior was different in earlier versions.
I can understand that adding a setting for this might be overkill, but I can't think of another solution right now.
Guess I'll have to make my own build reverting that PR for now.

**Comment by ssssamstrup** [comment]
I thought the tap to copy option was broken since it had stopped working. I'd also like for the behaviour to return to how it was. It seems unintuitive that the code isn't copied when tapping, when tap to copy is turned off. If a user doesn't want the behaviour they can turn the option off.

It's seems like a halfbaked introduction of how it works in that other app mentioned in #1120, which doesn't match the UI or UX of Aegis (which I prefer greatly). Keep it simple!

**Comment by anonymous-user** [comment]
I had the same issue. I thought tap to copy was broken until I realized I just had to tap twice to copy. I really wish we had an option to toggle the behavior.

**Comment by michaelschattgen** [comment]
@fusionneur  Ah yeah, I see what you mean. Unfortunately it's already too late to change this. Luckily the "minimize on copy" is not enabled by default so I assume you ran into a situation that the majority of our users haven't experienced. Thanks for letting us know though!
