### ISSUE TITLE
Upgrade from 1.3 2.x

### ISSUE THREAD

**Issue by battlerock** [beemdevelopment/Aegis#1087]
When trying to install the latest apk it tells me there is a conflict with the existing app.  Do I need to uninstall 1.3 and then install 2.x.  Will I need to back data before I do this?  Thanks

**Comment by alexbakker** [comment]
Upgrading to a newer version should never require a reinstall, unless the APK you're trying to update to came from a different source than the one you have installed currently. For example: If you installed Aegis through Google Play / GitHub, and you're now trying to update using an F-Droid APK, that won't work without a reinstall.

If you uninstall Aegis, you need to create a backup first so that you don't lose your data.
