### ISSUE TITLE
SVG logo

### ISSUE THREAD

**Issue by elliotwutingfeng** [beemdevelopment/Aegis#1097]
Could you provide an SVG version of your logo? Currently Aegis only has a PNG version. This makes it possible to for me to submit your logo to https://github.com/simple-icons/simple-icons , which only accepts SVG vectorised logos.

Aegis meets their >5k GitHub star popularity requirement, so it's a great opportunity to promote use of this project.

The closest I could find was this [logo](https://raw.githubusercontent.com/aegis-icons/design-assets/master/readme-banner.svg)

**Comment by krisu5** [comment]
> The closest I could find was this [logo](https://raw.githubusercontent.com/aegis-icons/design-assets/master/readme-banner.svg)

This logo isn't for Aegis the Android app, it's for my icon set **for Aegis** (and it's not really that close, there's huge difference 😅). Only relation is that [I and community](https://github.com/aegis-icons/aegis-icons) make icons for Aegis unofficially, I'm not part of dev team.

I don't think Aegis team has vector for the icon, because this was also asked in the Matrix chat room for different project and I image traced [the PNG](https://getaegis.app/images/icon.png) and tweaked the generated vector slightly from them.

This time I re-created it from stratch, since Simple Icons doesn't want image traced vectors. It's close at it gets IMO:

![Clipboard03](https://user-images.githubusercontent.com/3540275/221323664-d33bc0a4-d689-4ad0-b35e-5f7f7257d6bd.png)

If Beem Development doesn't have vector and is okay with my re-creation, **I personally** want to submit it to Simple Icons because:

1. I can fix the issues in vector
2. I created it, so I want the credit.

**Comment by elliotwutingfeng** [comment]
Alright, thanks! I'll leave it to you now.

**Comment by krisu5** [comment]
Submitted to Simple Icons: https://github.com/simple-icons/simple-icons/pull/8386

**Comment by alexbakker** [comment]
Took us a few days before we had time to get to this, but here you go: https://alexbakker.me/u/pn8frf828n.svg. That's all-black SVG of the Aegis logo. Because you intend to use this for Simple Icons, we've stripped the background shadow/tint so that the logo still looks good in one solid color.

**Comment by elliotwutingfeng** [comment]
> Took us a few days before we had time to get to this, but here you go: https://alexbakker.me/u/pn8frf828n.svg. That's all-black SVG of the Aegis logo. Because you intend to use this for Simple Icons, we've stripped the background shadow/tint so that the logo still looks good in one solid color.

Thanks all for your work! Really appreciate it!

**Comment by michaelschattgen** [comment]
Just checking in. How's the submission to simple-icons going? I noticed that both of your pull requests to simple-icons are closed.

**Comment by krisu5** [comment]
I might try it again some day, but not now because personal life and aegis-icons project. Or some else can take it.

There was miscommunication in the review process and it made me burn out for my submission.

**Comment by elliotwutingfeng** [comment]
@michaelschattgen Yes, please go ahead with a new PR.

@krisu5 I am sorry for the miscommunication in the PR review.
