### ISSUE TITLE
QR Code with https failure

### ISSUE THREAD

**Issue by jeffh2os** [beemdevelopment/Aegis#1107]
While trying to pair with a customers security 2FA (which normally uses PingID) I get a failure due to https.

An error occurred

An error occurred while trying to read the QR code.
com.beemdevelopment.aegis.otp.GoogleAuthInfoException: Unsupported protocol: https

Aegis from F-Droid
Version 2.1.2

**Comment by michaelschattgen** [comment]
Thanks for your report. The error you're getting means that you're trying to scan a QR code that's actually a URL instead of a 2FA (TOTP/HOTP) code. We've got a similar report yesterday #1106.

My guess is that the website you're setting up 2FA for is trying to redirect you to the Play Store to download a 2FA app and there's a second QR code somewhere in the set-up wizard.

**Comment by jeffh2os** [comment]
That would explain it then. Thank you for the quick response. We can close this out.
