### ISSUE TITLE
Feature request: add a copy button next to the codes

### ISSUE THREAD

**Issue by pbanj** [beemdevelopment/Aegis#113]
Would it be possible to get a copy to clipboard button next to the codes like andotp has? It makes it a bit quicker to grab the codes.

**Comment by michaelschattgen** [comment]
Hi pbanj, thanks for your contribution. We already have a similar issue here: #31. 

We don't like the idea of having a copy button next to the codes since it will make things look a bit messier, we are probably going for copy on a single press on the code itself.

Feel free to contribute to this discussion in the issue mentioned above.
