### ISSUE TITLE
'"repaired": true' showing up in my vault export?

### ISSUE THREAD

**Issue by chiraag-nataraj** [beemdevelopment/Aegis#119]
After I started adding custom images to my accounts and exported the vault for backup purposes, I noticed that the encrypted version says `"repaired: true"` under the slots section. Should I be concerned? I also have plaintext backups, so I can do a full purge and restore if need-be.

**Comment by alexbakker** [comment]
No need to be concerned. There was an issue in v0.4(.1) that prevented users with long passwords from unlocking their vault. The naming of that ``repaired`` field is a bit confusing, but if it's set to ``true``, the slot was checked for the issue, repaired if needed and is now known to have a good format. If it's set to ``false``, the slot has not been checked yet. Reparation occurs automatically if needed, so there's no need for users to do anything. You can read more about the issue here: https://github.com/beemdevelopment/Aegis/issues/95.

That bug had no impact on security, so it was only mentioned in the change log. We would have done a proper disclosure if that were the case.

**Comment by chiraag-nataraj** [comment]
Thanks for the info!
