### ISSUE TITLE
Main screen.  Display group name in entry.  Also setting to auto sort by group (with header line indicating group name)

### ISSUE THREAD

**Issue by golf247** [beemdevelopment/Aegis#1195]
New user coming in 100% because of the indication of groups feature.   I love the OSS nature, but slightly disappointed in the implementation of the grouping methodology.   Seems like it is more of a tagged info into the entry vs true grouping function.  I do really, really like that I can rename the issuer and change my sort method.   Some improvement thoughts below on the grouping aspect:

1. Is it possible to show the group name on the entry at the main screen (or at least have it be an option in the settings).  This would allow you to manually sort by group.
2. Is it possible to implement a setting toggle that allows you to sort (not filter) by group and have the group display as a header line or a collapsible/expandable folder on the main screen.   That was the expected group functionality I was picturing (similar to keepass groupings display).   Even just adding a sort by group (and implementing the first request) might accomplish most of what I'm looking for in the initial view I'd want to see when dealing with >50 2FAs.

**Comment by michaelschattgen** [comment]
Thank you for your report, we understand that the current implementation of groups is lacking UX and we made some technical changes a while ago which now allows us to improve the group functionality. One of these changes is the ability to assign an entry to multiple groups. Having an entry assigned to multiple groups doesn't work well with headers in our opinion since it's possible you'll see a lot of duplicate entries. We also like to keep our entries as compact as possible and we don't think adding more information (the group name) on the entry is worth the extra clutter.

We'll be working on improving the group feature but we currently don't see any fit of the two proposed solutions, I'll close this issue for now but feel free to comment your thoughts and ideas on this group feature so we can take that into consideration.
