### ISSUE TITLE
Biometrics without encryption

### ISSUE THREAD

**Issue by olfek** [beemdevelopment/Aegis#1198]
I want to use my screen lock with the app _without_ encryption

thank you

**Comment by alexbakker** [comment]
We don't have plans to add support for that. See: #212.

**Comment by olfek** [comment]
@alexbakker 

That whole discussion is basically irrelevant because they are talking about:
screen lock + screen lock dependent encryption

I'm suggesting only a screen lock with no encryption.

Currently I use the app without encryption.

I just want you to display my screen lock when I open the app.

**Comment by olfek** [comment]
@alexbakker 

Option 1 in your comment.

https://github.com/beemdevelopment/Aegis/issues/212#issuecomment-532873034

**Comment by olfek** [comment]
The usual flow minus https://developer.android.com/training/sign-in/biometric-auth#crypto

**Comment by alexbakker** [comment]
The reason I linked that issue is because there I explained why I think providing additional security options, like the one you're suggesting, is not a good idea.

To summarize: Providing multiple levels of security options is only going to confuse non-technical users, because it's difficult for them to tell which one provides actual security: "Why do I need encryption if the app is protected with biometrics?". Like I said in #212, some other apps in this space have taken the flexible security thing too far and we should be careful not to make the same mistake.

Also, the security of a biometric prompt without encryption basically boils down to trusting us (and Android) to not have a bug in the UI logic that allows bypassing the prompt. We already have a much better setup for biometrics. Use that.

**Comment by olfek** [comment]
> Providing multiple levels of security options is only going to confuse non-technical users, because it's difficult for them to tell which one provides actual security: "Why do I need encryption if the app is protected with biometrics?".

This one is easy to solve, just leave a little note saying "screen lock only" does not provide encryption.

> some other apps in this space have taken the flexible security thing too far and we should be careful not to make the same mistake.

It will be fine. I and the community can review your code 😛

> the security of a biometric prompt without encryption basically boils down to trusting us (and Android) to not have a bug in the UI logic that allows bypassing the prompt.

I do trust you, and Android, if there is a bug, rest assured, **_we, the users,_** will find it 🙂

> We already have a much better setup for biometrics. Use that.

I don't want encryption.

**Comment by olfek** [comment]
Let's say you ignore this feature request.

And the following scenario unfolds in my life.

1. Someone (Bob) has somehow obtained a copy of all my passwords.
2. I'm walking on the street, browsing my phone unlocked.
3. Bob grabs my phone and runs away with it making sure to keep it unlocked.
4. Bob gets home, makes a cup of tea, sits down, opens my Aegis app and proceeds to destroy my digital life.

If this feature was implemented, Bob would open the Aegis app, and be greeted with a biometrics prompt.

You could argue that because only a screen lock exists _without_ encryption, Bob could root the Android phone and gain access to the unencrypted data, _assuming Bob has those skills_. Therefore screen lock _with_ encryption would be the best solution.

But my original requirement was "I don't want encryption", meaning users in this audience, would choose no screen lock over a screen lock + encryption, and so Bobs life becomes easier, as there is no screen lock, Bob can gain access to the data without using his software engineering sillks.

What do you think? @alexbakker

**Comment by jdreesen** [comment]
Out of curiosity, why don't you want encryption?

**Comment by alexbakker** [comment]
@olfek If that scenario unfolds in your life, I'd tell you that you should have listened to the "enable encryption" recommendations in the app. By doing so, no matter how skilled Bob is or how outdated your device is, he won't be able to see the contents of your Aegis vault without decrypting it first. And Bob seems pretty skilled since he apparently managed to obtain a copy of all of your other passwords (?!).

The goal is to provide one good setup that provides protection in case someone gains access to your device or Aegis vault file. No customization options to sprinkle some prompts here and there to protect against specific scenario's. I'd rather get rid of the plaintext option entirely, than introduce more customization here.

**Comment by olfek** [comment]
@jdreesen 

> Out of curiosity, why don't you want encryption?

I think this meme explains it quite well

<img width=500 src="https://github.com/beemdevelopment/Aegis/assets/27283110/f9bd5aef-88b6-43d8-b20c-cefe83b35e03" />

With too much security, you can end up locking yourself out, I like to secure things when and where **_needed_**.

And for my use case with these OTP codes, I want the security that a screen lock provides, but feel that the security provided by encryption is overkill.
