### ISSUE TITLE
Drop down list view of tokens

### ISSUE THREAD

**Issue by zeoint** [beemdevelopment/Aegis#1219]
1. Based on the groups in aegis, the drop down list view of token can be created.
2. Provide an option to view the token in drop down list form based on groups in Appearance -> View mode -> Drop down list.
3. If no group is assigned to the tokens in this view mode, then assign that tokens into no group drop down list.

---

![0](https://github.com/beemdevelopment/Aegis/assets/127277950/ff34848f-d65a-455d-9653-19d13f15c3af)

**Comment by michaelschattgen** [comment]
I like this idea but our entries currently support assigning to multiple groups which is the reason why I don't see this work properly. What would happen if an entry is assigned to "Github" and to "Work" and to "Productivity" in this example?

**Comment by Bazoogle** [comment]
> I like this idea but our entries currently support assigning to multiple groups which is the reason why I don't see this work properly. What would happen if an entry is assigned to "Github" and to "Work" and to "Productivity" in this example?

To me, the current implementation of groups sounds more like tags, since it can be assigned multiple groups. It's like having a "school" and "productivity" tag assigned to it. This feature request seems more like folders. Both could be implemented, but of course that would be a good amount of restructuring. But then you could either filter certain tags, or go to your groups however you prefer.

Personally, I just always use the search feature (Bless you guys for the focused search on start), but I could see it being useful for others.

**Comment by catscandrive** [comment]
I would love ve to ability to open the app to my tag/group list.
