### ISSUE TITLE
Add an option to sort OTPs per last usage time.

### ISSUE THREAD

**Issue by rustforfuture** [beemdevelopment/Aegis#122]
Hello

Please add an option to sort OTPs per their last usage time.
what i mean is like andOTP

Thank you

**Comment by alexbakker** [comment]
Can you be a bit more specific? What would qualify as "usage"?

**Comment by mdmk** [comment]
I think he means sending the last entry used to the top.

To send entry top top, it would imply the user reveal or copy the code. In fact, if entries are not hidden and user does not click, there is no way to know an entry is used.

The option should be added to the 'sort by' button, to complement sort by account and sort by issuer.

**Comment by 3j9fkyahunqoxwqu** [comment]
Thanks @mdmk 
I Exactly wanted to say this.

**Comment by michaelschattgen** [comment]
Thanks for your clear explanation @CouldBeThis. We have recently made some changes to our interaction (#173) which makes sorting entries by 'usage' possible. The following will be available in new versions of Aegis:

- **Tap**: copy code to clipboard
- **Hold**: enter ActionMode which allows you to edit and delete the highlighted entry
- **Drag and drop**: after entering ActionMode you can drag and drop the highlighted entry

We can now record the amount of usages since tapping on the code will now 'only' copy the code. We can combine this with some 'Dim on tap' preference which will dim all the other codes for a set amount of seconds (i.e. 10/15 seconds). I'm not a big fan of making the entries bigger and I think dimming the rest of the entries will be good step forward. 

What do you think @alexbakker? Do we need another issue of the dimming part?

**Comment by CouldBeThis** [comment]
Thank you, I posted this before that change had been made but GH didn't make it visible because they didn't like me email address and it took me this long to get it sorted out. 

I'm waiting for the new version to come up on F Droid so I can use it, looking forward to that. 

Thank you for being so very responsive that you read my mind. ;)

**Comment by CouldBeThis** [comment]
Hello, 

Having updated Aegis from F Droid a few times I was hoping the "last used on top" feature would show up. I thought this was on the way.  However, in rereading the last comment by @michaelschattgen I wonder if perhaps I misinterpreted. 

Which is the correct understanding of current situation?

A. Sort by last use is implemented, or
B. Something else has been implemented which now makes sort by last use _possible_ but not yet implemented

Thanks for your time in everything.

**Comment by michaelschattgen** [comment]
It's indeed B, unfortunately. We've made changes to the way our users interact with the tokens which made it possible for us to 'track' the usage of each token, we just didn't implement it yet.

However, this feature will be implemented in Aegis eventually!

**Comment by rugk** [comment]
I agree this would be *very*, *very* useful.
I do use the "dim" and "hide" option, so this feature would be totally useful (if either of this option is selected, actually).

Also, it makes it very useful for many entries, because one may not really know what entries are actually used and which accounts are just legacy.
So actually, I would rather propose (another option) to **sort by usage count**, i.e. most used account is at the top, legacy ones at the bottom. After a few rounds of normal usage, thus the sorting gets useful and the more you use the app, the more it "increases" UX, somewhat…

Because sorting by name or whatever it you currently can do is arbitrary – compared to sorting the accounts you use most/often/recently at the top (so you can access them quickly).

**Comment by alexbakker** [comment]
@rugk 

> So actually, I would rather propose (another option) to sort by usage count, i.e. most used account is at the top, legacy ones at the bottom. After a few rounds of normal usage, thus the sorting gets useful and the more you use the app, the more it "increases" UX, somewhat…

I like that idea. The downside would be that a token that was very frequently used in the past, but is no longer used currently, will stay at the top for quite a while before the other tokens can catch up with its usage count.

**Comment by rugk** [comment]
Yeah, possibly then reset that token count after 14 days or so? Or calculate some "score" based on "last usage" + "usage count", together?? You could improve that algorithm endlessly, I guess…

**Comment by alexbakker** [comment]
Clearly, the only solution is to apply some machine learning here /s.

**Comment by rugk** [comment]
Well… you could certainly call it "artificial intelligence" depending on your definition. :laughing:

**Comment by alexbakker** [comment]
You're right that we ended up going in a different direction than the initial proposal here. The issue was closed, because we thought the usage count sorting feature we implemented instead would be better and also satisfy most people looking for a plain sort by last used. If you have a compelling reason why this doesn't work for you, and think we should also implement a sort by last used, feel free to open a new issue and we can discuss it there.
