### ISSUE TITLE
Crashes every time when the screen is locked

### ISSUE THREAD

**Issue by RDKRACZ** [beemdevelopment/Aegis#1228]
### Version

2.2.2

### Source

Google Play

### Vault encryption

Yes (with biometric unlock)

### Device

Motorola Edge 30 Neo

### Android version

13

### ROM

Stock

### Steps to reproduce

-Open and unlock Aegis. It can be left on any "screen" (main, settings, searching, or editing, it doesn't matter as long as the vault is unlocked)
-Lock the device screen
-Unlock the device and notice the Aegis closed(?) itself. It also disappeared from the recent apps switcher.

### What do you expect to happen?

Aegis should still be there when I unlock the device and it should be asking to authenticate again

### What happens instead?

Described above

**Comment by alexbakker** [comment]
This is expected behavior when "Automatically lock Aegis when the device is locked" option is enabled. The reason for this behavior is explained in more detail here: https://github.com/beemdevelopment/Aegis/issues/731#issuecomment-835486449. The workaround we had for Aegis disappearing from the recent apps list stopped working in recent Android versions (Which was to be expected, as we were calling a private method through reflection)
