### ISSUE TITLE
Missing Button

### ISSUE THREAD

**Issue by mdmk** [beemdevelopment/Aegis#123]
If vault is encrypted, the filter button disappear, it is replaced by lock button.
Expected behavior should be to have the 4 buttons when vault is encrypted.

Without encryption (notice the filter button on the left):

![](https://i.imgur.com/JPyiYh2.png)

With encryption (notice the filter button is replaced by the lock button):

![](https://i.imgur.com/wvATUYV.png)

**Comment by alexbakker** [comment]
We can only specify 2 icons that should be shown at all times. The others are only placed on the bar if there's room and the Android framework decides what "room" means. Forcing all icons to be shown would go against the user interface style guide.

As a side note, we're probably going to move the "Lock" icon to the sub-menu soon, so that the icon placement is consistent between plain text and encrypted vaults.

**Comment by mdmk** [comment]
OK thanks for the explanation.
A consistant look seems a good idea, but I think lock button is more important than filter if you have to choose a common default.
Being able to quickly lock is a security feature, even if filters are one more click away it is less critical.
I admit the back button lock the vault but it is less intuitive visualy.
Anyway thanks for information.
