### ISSUE TITLE
Red timer bar should be more visible

### ISSUE THREAD

**Issue by daveTheOldCoder** [beemdevelopment/Aegis#1250]
I was going to request a feature to add a timer that shows much time is left before the codes refresh. While looking to see if the request had already been made, I found some existing issues that discussed it and learned that the feature is already present. :)

I think that shows that the red timer bar at the top needs to be more visible.

Making it about four times thicker would help.

**Comment by alexbakker** [comment]
Could you share a screenshot of what the main view with the progress bar looks like on your device?

**Comment by daveTheOldCoder** [comment]
Here it is.

![screenshot](https://github.com/beemdevelopment/Aegis/assets/55119684/6f5f75f1-e017-4173-8bee-033d900533ef)

**Comment by alexbakker** [comment]
The reason I asked for a screenshot is to double check that it doesn't look different on your device than others for some reason. But no, this is what it's supposed to look like. The progress bar already stands out with its red color and it will stand out even more when #1227 is merged, because the toolbar will probably have a much lighter color.

Thanks for the suggestion, but I don't think there's anything we need to change here.
