### ISSUE TITLE
MFA push notifications in combination with selfhosted ntfy (=DIY Authy)

### ISSUE THREAD

**Issue by alexanderadam** [beemdevelopment/Aegis#1259]
I'm not quite sure whether this is possible and whether the issue title explains properly what this is about.
The general idea is to improve usability for 2FA.

So for 2FA users might have to unlock their mobile phone, open Aegis, search the relevant application and then they can actually start to type in the code manually or copy the code.
However, the company Twilio created a smart solution for making this work-flow easier: [_Authy_](https://authy.com/).
[Authy's workflow goes as follows](https://authy.com/blog/authy-onetouch-simply-strong-security/):

> the application calls Authy when it wants 2FA assurance. Using Apple or Google, Authy sends a push notification to the user’s device, which improves the user’s experience by leading the user to the mobile app. This push notification does NOT contain the transaction details.

This work-flow sounds great and clearly removes friction. But currently it relies on a proprietary and uncontrollable service. Such as most push notification infrastructures. However, there's [ntfy](https://github.com/binwiederhier/ntfy#ntfysh--send-push-notifications-to-your-phone-or-desktop-via-putpost).
And this work-flow obviously relies on push infrastructure anyway.

Therefore it would be nice to also have a free and FOSS solution to improve people's security and make their lifes easier.

Without knowing any details about Android development I would guess that it would need these things:

1. The server must have an integration possibility so that services and applications can actually provoke this. The best way would probably to mimic [the Authy API](https://www.twilio.com/docs/authy/api#api-base-url), since other developers only would have to give the config option to change the API URL then. I created [an ntfy issue](https://github.com/binwiederhier/ntfy/issues/250#issue-1235566260) for that.
2. Either Aegis can fetch the push notification directly or it needs to be done with the [ntfy Android app](https://github.com/binwiederhier/ntfy-android#ntfy-android-app) as a proxy but there should be a possibility to open a particular entry from Aegis app (_maybe it would be good to discuss that [with the ntfy maintainer](https://github.com/binwiederhier) [[Discord](https://discord.gg/cT7ECsZj9w) / [Matrix](https://matrix.to/#/#ntfy:matrix.org)]_). Maybe it would work with a custom schema (_i.e. `otpauth://totp/some_email_provider`_ — [this issue](https://github.com/beemdevelopment/Aegis/issues/1147) might need to be revived then and [something like this](https://developer.android.com/training/app-links/deep-linking) might be relevant too).

I'm fully aware that this is a lot to ask but improving security and its usability for people believing in free software is a probably  worth a try.

**PS:** Thank you so much for Aegis :raised_hands:

**Comment by alexbakker** [comment]
Personally, I don't see the big usability win here. You're only skipping the step of searching the right entry in Aegis. Users still have to tap (in this case the notification) to open Aegis, unlock the app and then enter the OTP into the website.

It's also good to keep in mind that:
- Aegis is not going to request the internet permission.
- Services are unlikely to do any work on their TOTP stuff now that passkeys are gaining traction.
- Services are very unlikely to implement support for this unless there's a proper spec and support in 2FA apps. It's a bit of a chicken and egg problem.

I don't want to reject this outright though, since it sounds like 2FA apps like Aegis only have to implement support for deep linking. I'm sure we can figure something out, like applying a search filter in Aegis via a deep link. Once you have a draft of the spec, feel free to open a new issue so that we can discuss what would be required of Aegis and whether that's something we can accommodate.
