### ISSUE TITLE
Show groups on main screen and allow expand/collapse of groups

### ISSUE THREAD

**Issue by chiraag-nataraj** [beemdevelopment/Aegis#126]
Groups are a fantastic idea, especially as the number of 2FA accounts goes up, but the way it currently works, you can only show one group at a time and you have to go into the overflow menu. It might be better to display them as headers with the option of expanding/collapsing each one independently.

**Comment by ztNFny** [comment]
I'd love to see "group by group" (show a headline, then the items belonging to the group) and "sort by group" options.

**Comment by JNavas2** [comment]
+1
As it is now, Groups are more like _Profiles_, a use case I don't need.
What I need is Groups as a Tree View, with expand and collapse,
because that saves screen real estate with Groups collapsed by default.
And that also works well for the Profiles use case, with no filtering needed.
Please give this serious consideration. Thank you.

**Comment by michaelschattgen** [comment]
Closing this issue as we don't have plans to implement this. We do have plans to support labels instead of groups which removes the need for this feature.

**Comment by JNavas2** [comment]
That's unfortunate. I had been cautiously optimistic that I could start recommending your app to clients and followers, but this (lack of) response will force me to step back, rethink and evaluate alternatives. And it could affect my review rating, in part because I doubt you spent much time understanding our use case, a red flag, since labels would not seem to address it either. But we can't know for sure without more information. What exactly are your plans, and when will they be implemented?

**Comment by alexbakker** [comment]
> But we can't know for sure without more information.

This is a fair point. As you may have noticed, we've been closing a bunch of old/stale issues today and this is one of the few that was left a bit open ended. We'll make sure to create a new issue with our plans first before closing others in the future. You can expect an issue to be created for this matter before the end of this weekend.

> What exactly are your plans

Briefly, the idea is that instead of being able to assign one group per entry, you'd be able to attach multiple labels per entry. The main view would then offer an option to filter on multiple labels at once. Each entry will also show the list of labels that are attached to it. Nothing is set in stone yet, so we may have to go back to the drawing board at some point.

> and when will they be implemented?

As always, there is no timeline, we work on this project in our free time.

**Comment by ztNFny** [comment]
For me it doesn't matter whether it's called label or group, one or multiple can be assigned (in that regard I'm ok with the current groups but don't mind more flexibility). What's missing for me is an easy way to filter. The current one, hidden in menu, is too many clicks to be usable.
My sinple suggestion would have been to have the groups as collapsible "folders" on the main screen. If instead we get something like a line of labels at the top of the screen and the list below being filtered accordingly thats ok for me. Main point is that it should be 1 click from main screen to show/hide items.

**Comment by JNavas2** [comment]
@alexbakker
Thank you. I appreciate that insight. Unfortunately, it still seems a lot like profiles, albeit more flexible than groups, and does not seem to really address this use case: I have multiple accounts at certain providers (in part because I serve many clients). To avoid a clumsy, very long list, I'd like to be able to expand and collapse all of the accounts for a given provider, like folders in a tree view; i.e., instead of the left view below, I'd like the right view (with Domain expanded by a touch). I could Label by client (1, 2, 3, ...), but doing that would seem to be complicated/clumsy, unless I'm missing something.

<img width="320" alt="nj5cJxdj8W (Custom)" src="https://user-images.githubusercontent.com/14850792/86517942-ebd33480-bde1-11ea-862b-d76e2d61316a.png">
