### ISSUE TITLE
View mode - Tiles - Allowing hiding account name to make issuer larger

### ISSUE THREAD

**Issue by chylex** [beemdevelopment/Aegis#1285]
Hi, I like the two-column layout of the Tiles mode, but the name of the account and issuer are too small for me to read.

Here is a screenshot scaled down to 40%, to make its size closer to how it actually looks on my phone, due to the disparity between screen resolution and physical size:

![image](https://github.com/beemdevelopment/Aegis/assets/3685160/2840727d-ef90-46c4-a5c8-ce9d4210f1da)

Compared to the font size of the digits, the backup warning, or the app title, the names of the services are much smaller which makes them really hard to read.

I noticed that with Tiles mode, it always displays both the account name and issuer, and it's not possible to change that setting. Would it be possible to have that setting hide the account name, which would clear up space for the issuer font to be larger?

**Comment by rafaelazvdo** [comment]
The names in tile mode were actually a bit small, we can compare them with Authenticator Pro, which has the same display mode but the names are a little bigger and easier to read.

**Comment by ckantor8** [comment]
I was so disappointed to find this exact problem. I love Tile Mode because I barely have to scroll, but I like hiding the usernames just for the sake of privacy/security. Seems odd to me the app still has a specific point in the settings that appears to tell you this is impossible. Not sure why the feature couldn't just behave the same in Tile mode as the other modes. Would be very much appreciated!
