### ISSUE TITLE
Ui feedback

### ISSUE THREAD

**Issue by fiorins** [beemdevelopment/Aegis#1317]
Hi, I'd like to give you feedback relating to the app. I've been using the app for a while together with others and I noted some things that could improve the user experience.

- Icon management like that one in Authenticator Pro, allows the user to move between packs and search for icons more easily.

- Use the bottom bar as most other apps, by placing 3 buttons, such as Settings, Search, and Add (or by placing it as the floating icon).

- While at the top screen keep 2 icons such as: sorting and archive. Tapping on the Archive icon shows entries in the Archive (with the Archive icon being replaced by one of the Home or other) and vice versa when it is clicked again.
Consider whether to leave the three dots there or put another icon in the bottom bar that encloses them.

I also saw that it is moving on to new material design3. Great!

**Comment by rsb-23** [comment]
Additionally, can group filter icon be moved beside sort icon?
Ref: https://github.com/FossifyOrg/Phone
![image](https://github.com/beemdevelopment/Aegis/assets/57601627/53b47d81-37d7-461d-ae28-bedaeca600e8)

**Comment by fiorins** [comment]
![Screenshot_20240418_150051.jpg](https://github.com/beemdevelopment/Aegis/assets/32281481/ad28e73e-6fe6-4e12-9c68-4d7b3c52f72e)

Like this one, or with the floating icon inside the bottom bar.

I just changed the groups icon so as not to confuse it with the sorting icons.

**Comment by michaelschattgen** [comment]
Thank you for your feedback. While I do agree Aegis can use some improvements on its UI / layout, I don't see a bottom app bar like that getting implemented. We do our best to follow the Material guidelines and according to [those](https://m2.material.io/components/bottom-navigation#usage) the bottom app bar should be used for navigation to multiple primary (or rather top level) destinations, we currently only have one.

I'm closing this issue since it's too ambigious, but feel free to keep the conversation going since we're all ears for improvements on our UI.
