### ISSUE TITLE
Code near botton of screen is obscured

### ISSUE THREAD

**Issue by JonnyTech** [beemdevelopment/Aegis#1328]
### Version

v2.2.2

### Source

F-Droid

### Vault encryption

Yes

### Device

Moto E series

### Android version

Android 13

### Steps to reproduce

Click to reveal an entry near the bottom of the screen

### What do you expect to happen?

Code to be shown unobscured

### What happens instead?

![IMG_20240325_022302](https://github.com/beemdevelopment/Aegis/assets/3584732/bb4d246b-a839-41eb-9510-1dac1c30d846)

**Comment by michaelschattgen** [comment]
The alert that is obscuring the code is coming from Android whenever you copy something, we do not control that alert from within the app. I'm not entirely sure what a good fix for this could be. 

If it bothers you because you just wanted to reveal the code you can always set "Copy to clipboard" to a double tap instead of a single. Would that work for you?

**Comment by JonnyTech** [comment]
Thank you for your prompt reply. Hmm, I had considered that was an Android feature. Could you insert blank space / padding / empty entries at the bottom of the list to compensate?

Thanks for the double tap suggestion, that is a suitable workaround as I usually use Aegis on my phone to unlock items on my computer.

I shall leave this open in case you want to muse about layouts. Feel free to close.

**Comment by michaelschattgen** [comment]
Glad to hear the double tap suggestion solves this issue for you. We've discussed this topic internally and don't think we're adding extra padding at the bottom to account for this Android built-in feature as it will only confuse people and will look weird (in our opinion).
