### ISSUE TITLE
Regression as of 3.0: Group selection in view does not persist after closing

### ISSUE THREAD

**Issue by dimitris-personal** [beemdevelopment/Aegis#1329]
### Version

v3.0

### Source

Google Play

### Vault encryption

Yes (with biometric unlock)

### Device

Pixel 7 and Pixel 6A

### Android version

Android 14 AP1A.240305.019.A1

### Steps to reproduce

- Upgrade from previous 2.x release on Play Store to 3.0, with pre-existing groups and a group selection saved as default view contents.
- Unlock the vault - entries from all groups are shown.  This was not the default state under 2.x.
- Select only one group.
- Close the app (back gesture to home screen).
- Open the app again and unlock the vault.
- Before 3.0 this would maintain the group selection made above.  Now it goes back to showing all groups' entries.
- Workaround:  Toggle biometric unlock off/on.
- Group selection is again "remembered" between sessions.
- Side-effect:  This also seems to reset the state of last backup taken, bringing up the backup reminder banner even though there haven't been any new entries since last backup.

### What do you expect to happen?

Group selection was expected to be persistent.

### What happens instead?

Group selection is cleared.

**Comment by michaelschattgen** [comment]
Thanks for your report. Interesting, I can't seem to reproduce this and I can't recall any changes regarding this feature.

**Comment by dimitris-personal** [comment]
@michaelschattgen please see updated description.  Found a workaround, but this still seems to be a new sharp edge maybe worth addressing.  Most users may not look at github to find this or think of biometric unlock as related.

**Comment by alexbakker** [comment]
Losing the previously saved group filter is expected behavior when updating to 3.0, but not being able to save a new group filter is not.

We've made some internal changes to groups as preparation to allow entries to be in multiple groups. In short: groups are no longer internally identified by their name, but by a UUID. Upon launching the app, Aegis will detect that your vault file is in the old format, and it will convert it to the new one. During this process, all groups will receive a random UUID. This  happens in-memory and these changes are not written to disk until you make some other change (like enabling/disabling biometric unlock, as you discovered) that triggers a save of the vault. Changing the group filter is not an action that triggers a save of the vault, because the filter is stored elsewhere.

This causes trouble because after saving the group filter, it will contain a group UUID that will no longer exist after you relaunch the app.

**Comment by andbenn** [comment]
When I had this problem, toggling various groups trying to get it to save and stay on a restart, I noticed that at certain times, the back motion would take me back to a list of tokens, usually what I just had up and was trying to escape from.  I thought this strange.  Maybe some view of the original data.  Since toggling biometrics, I'm back to being good.  Thanks team for such a nice app!

**Comment by RavenStryker** [comment]
> @michaelschattgen please see updated description. Found a workaround, but this still seems to be a new sharp edge maybe worth addressing. Most users may not look at github to find this or think of biometric unlock as related.
> 
> Edit: Workaround also seems to have a (not so important) extra side effect.

Thanks for this, I was wondering what was happening as the app looked different so I assumed it was an update. I can confirm I had the same issue and was also able to get it to work around that by toggling biometrics as well. Cheers!

**Comment by pedroapero** [comment]
In my case, after upgrading to 3.0, the display was all scrambled. Couldn't see anything on the settings menu.
After uninstalling and re-installing (and re-importing my data); it is working fine.
I'm on Android 8.1.0.
