### ISSUE TITLE
icon packs are no longer updated

### ISSUE THREAD

**Issue by userforsource** [beemdevelopment/Aegis#1339]
### Version

3.01

### Source

Google Play

### Vault encryption

Yes (with biometric unlock)

### Device

Pixel 6

### Android version

android 13

### ROM

stock

### Steps to reproduce

The link that aegis is providing is no longer updated
https://aegis-icons.github.io/
https://github.com/aegis-icons/aegis-icons/issues/
No longer actively maintained so please remove this option or chnage it to something else.

### What do you expect to happen?

Monthly update

### What happens instead?

No update for 8months.

**Comment by michaelschattgen** [comment]
While I agree that the icon pack is not actively maintained, it's still a really good option for our users since it covers most of the websites/services that have 2FA enabled. Unless this icon pack starts missing a lot of new icons or until we have a better alternative I don't see it getting removed from the app.

What do you think @alexbakker ?

**Comment by userforsource** [comment]
Removing it makes sense as it was a unofficial side project not officially so remove this and until unless we get a better alternative or this project again start maintaining.

**Comment by alexbakker** [comment]
@michaelschattgen Agreed. aegis-icons is still the best icon pack.
