### ISSUE TITLE
Add reminder dialog for passwords

### ISSUE THREAD

**Issue by michaelschattgen** [beemdevelopment/Aegis#145]
When Aegis is setup to use fingerprints, an additional password is required. The (fingerprint) keys in the AndroidKeyStore become permanently invalidated once a new fingerprint is enrolled or all fingerprints are unenrolled.

Users tend to forget their password used in the onboarding of the app, which results in failing to unlock the vault thus the loss of their tokens.

It would be nice to have some reminder dialog pop up every x unlocks which allows the user to type in their password so the possibility of forgetting the password will be smaller.

**Comment by mdmk** [comment]
Android does something pretty much similar for lockscreen.
If you have fingerprint enabled, it will ask you for pin, schema or password the first time you unlock phone.
It will never ask it again as long as the phone is not rebooted or there is not too much fingerprint errors.
I think a similar security system would be appropriate for Aegis, perhaps from the start of the app as long as it is not killed (but would be a bummer if pseudo kill with swipe in task switch does reset the thing).

**Comment by p0358** [comment]
Some ROMs do the actual kill with swipe in task switch :)
I was actually surprised that AOSP doesn't...

**Comment by vertigo220** [comment]
I will just add that this should be optional, or at the very least it shouldn't require you to actually enter the password on the initial run. But this is something about Authy I don't particularly like, being constantly pestered by the reminder dialog, which I have to hit cancel on in order to get in and get the code I came for. It's fine to even enable it by default, to help make sure less advanced users don't screw themselves, but it should ultimately be left up to the user how they ensure they remember their password. Personally, I put a password hint in my password manager (NOT the actual password, as that would defeat the purpose of this if my password and Aegis databases were somehow stolen and my password database cracked). I'll probably also put a scrambled form of the whole password somewhere else, so even if the hint in the manager isn't enough to fully jog my memory, I could combine it with that to remember what I did.
