### ISSUE TITLE
Export for google authenticator not working

### ISSUE THREAD

**Issue by databaze** [beemdevelopment/Aegis#1451]
### Version

3.0.1

### Source

F-Droid

### Vault encryption

Yes

### Device

Pixel 4a

### Android version

14

### ROM

GrapheneOS

### Steps to reproduce

Trying to use the "export for google authenticatior" feature to export vault to iphone SE with Google authenticator steps:

On Pixel:

-Open Aegis
-Go to Settings
-Import & Export
-Export for Google Authenticator
-QR Code generated 1/4 QR codes

On iPhone:

-Open google Authenticator
-Press + sign
-Scan qr Code
-10 accounts imported
-Press + sign again
-On Pixel press next to show second qr code
-Scan code with iPhone

Error: Incorrect QR code. Make sure QR code 1 of 4 is displayed on your other device

 

### What do you expect to happen?

be able to scan all qr codes and add all accounts

### What happens instead?

can only add 10 accounts linked to first qr code

**Comment by alexbakker** [comment]
What happens when you scan that first QR code on your iPhone, precisely? Does it close the QR code scanner on its own and report "10 accounts imported", without any interaction from your side?

It's supposed to keep the QR code scanner open and ask for the next QR code. I've just confirmed that this works correctly on Android.

**Comment by alexbakker** [comment]
Is there a separate "Transfer account" menu (like the Android version of Google Authenticator) that you could try instead of the + button? I don't own an iPhone, so I'm not able to test the iOS version of Google Authenticator.

**Comment by databaze** [comment]
> Is there a separate "Transfer account" menu (like the Android version of Google Authenticator) that you could try instead of the + button? I don't own an iPhone, so I'm not able to test the iOS version of Google Authenticator.

Yes, there is but only for exporting accounts from Google Authenticator, not for importing...

**Comment by IntuitiveCore** [comment]
My export link is DISABLED and does nothing. Import works but why is my export Dead?

**Comment by ballpumpe** [comment]
> My export link is DISABLED and does nothing. Import works but why is my export Dead?

I had the same situation. You need to set a pin, password, fringerprint etc. on your device.
When you set this up, the option will be clickable.

**Comment by michaelschattgen** [comment]
@IntuitiveCore @ballpumpe what "export" link are you talking about exactly? As far as I know we don't have any criteria for our export button to be disabled.

**Comment by ballpumpe** [comment]
> @IntuitiveCore @ballpumpe what "export" link are you talking about exactly? As far as I know we don't have any criteria for our export button to be disabled.

I apologize for the confusion. I thought the comment from [IntuitiveCore](https://github.com/IntuitiveCore) was about exporting from Google Authenticator (which I believe it was). My comment was referring to the Google Authenticator app. To export from the app, you need to enable a screen lock with a password or a similar method; otherwise, the export button won’t work.

**Comment by michaelschattgen** [comment]
@ballpumpe no need to apologize at all! I was just making sure you guys were not talking about Aegis. I was unaware of such behaviour in Google Authenticator, so that's good to know. Thanks for clearing up the confusion!
