### ISSUE TITLE
"Fingerprint" checkbox does not get set to false after enrolling a new fingerprint

### ISSUE THREAD

**Issue by michaelschattgen** [beemdevelopment/Aegis#146]
Aegis disables the ability to unlock with the vault with your fingerprint when a change has been detected in the device's security settings, in order to enable fingerprint again you have to re-enable the "fingerprint" checkbox in the preferences activity.

However, this checkbox stays checked even when fingerprint unlocking is disabled by Aegis because of this change in the security settings.

Follow the following steps to reproduce:

- Have an encrypted Aegis vault set up with fingerprint unlocking enabled
- Remove or enroll a fingerprint in your Android settings
- Open Aegis and unlock the vault by entering your password
- Open settings in Aegis

You should see that the 'Fingerprint' checkbox is still checked and requires you to double tap it in order to use fingerprint unlocking again. This checkbox should be unchecked at the moment Aegis sees a change in your security settings.

**Comment by alexbakker** [comment]
Just to clarify, this is actually semi-intentional. When Aegis notices that the key in the Android KeyStore has been invalidated, it only shows a warning in AuthActivity. It does not immediately remove the fingerprint slot from the vault. That's why that checkbox in the security settings is still checked. Only when the user unchecks the checkbox, the fingerprint slot and the Android KeyStore key are removed.

When I was implementing this I wasn't sure whether automatically removing a slot from the vault was a good idea, so I decided not to and kept it simple.

Anyway, I agree that the current behavior may be confusing to users and we should think of a way to improve it. I'm just not sure how.

**Comment by alexbakker** [comment]
We decided that we're going to leave this as is.
