### ISSUE TITLE
[Feature] Support for Authy's 7-Digit Non-RFC TOTPs

### ISSUE THREAD

**Issue by anindyamaiti** [beemdevelopment/Aegis#147]
Some service like Gemini and Twitch TV support OTP via Authy's proprietary algorithm **only**. Authy uses a [slightly modified TOTP](https://gist.github.com/JacobJohansen/5f688d45049be440b8ee87cc5e854b75) 8-digit generator, and uses only the [last 7 digits](https://randomoracle.wordpress.com/2017/02/15/extracting-otp-seeds-from-authy/). It will be awesome if a feature to support Authy's 7-digit TOTP is added. 

Direct import from Authy will also be great. Currently Authy's 7-digit TOTPs are ignore when importing in to Aegis, only the regular RFC compliant TOTPs are imported. Steam import worked great so I am hopeful we can do the same for Authy's (stupidly complicated) OTPs some day soon. Thanks.

**Comment by alexbakker** [comment]
This looks like TOTP with some non-standard parameters to me. Non-standard digits counts and periods are already supported, so this should just work. We just need to add support for it to our importer code.

Did you try to extract and add those tokens to Aegis with that script you linked? Did it work?

> Currently Authy's 7-digit TOTPs are ignore when importing in to Aegis

Did Aegis show an error for those tokens or were they silently ignored?

**Comment by anindyamaiti** [comment]
> Did you try to extract and add those tokens to Aegis with that script you linked? Did it work?
Yes, I tried to extract the secrets from Authy using the script in the link. However, the secrets looked like in base-10 and it did not work. I converted it in to base-32 but that didn't work either. I also played around with the hashing algorithm and time, nothing worked.

> Did Aegis show an error for those tokens or were they silently ignored?
The 7-digit TOTPs were silently ignored. They did not appear in the import list.

**Comment by MarioMasta64** [comment]
[some info on extracting totp codes from authy](https://gbatemp.net/threads/extract-your-totp-keys-from-authy-using-chrome.487030/) (or [here for just the script](https://mariomasta64.me/scripts/))

authy codes can be extracted using this (deleted ones and 7 digit ones as well)

and the middle two digits are repeated, aegis already supports it and andotp natively makes the change needed, and if you want you can follow the directions there to extract a qr code for aegis to make things easy or you can do it manually

for manual directions:

you can run a console on the chrome authy app and look at the results from this: `console.log(i);` it should give you anything you want to see if you explore enough

you have to first hex to base32 encode i.decryptedSeed for what you want to use then the code length is 20 seconds however the actual timer is 10 seconds (in-app authy codes skip every other code because 10 seconds is kind of short, both codes technically work when entering on sites however so possibly add an option to skip every other code?)

**Comment by alexbakker** [comment]
Took a quick look at this. It looks like the secrets for those proprietary Authy tokens are located in ``com.authy.storage.tokens.authy.xml``. We can probably add support for that to the existing Authy importer
