### ISSUE TITLE
Show Next Code: easier font color

### ISSUE THREAD

**Issue by andbenn** [beemdevelopment/Aegis#1556]
With the Show Next Code option enabled, the next code is displayed in a smaller font below the main code.

Could the color of the font be made slightly darker for light theme mode, and slightly lighter for dark/AMOLED mode?

As it is, it's difficult to read due to the lack of contrast.

**Comment by michaelschattgen** [comment]
Thanks for your report. I just created a fix which changes the following:

Left is before, right is after
![image](https://github.com/user-attachments/assets/1252ac6f-8fe4-4406-b7eb-e21da01aaf2b)
![image](https://github.com/user-attachments/assets/811d06eb-cb0e-4429-a263-a365f578d5c5)

While I agree that the codes should have better visibility; it's a challenge to not make it too prominent since we think the 'current' should always be the most obvious one. Hope this helps.

**Comment by andbenn** [comment]
Thanks.  I understand the prominence/current scenario.  These slight changes should be fine to improve readability and I appreciate your effort!
