### ISSUE TITLE
Aegis Vault unlocks with both "Vault password" and "Backup & Export password" when separate password is set for backups

### ISSUE THREAD

**Issue by punkajk** [beemdevelopment/Aegis#1580]
### Version

3.3.2

### Source

Google Play

### Vault encryption

Yes (with biometric unlock)

### Device

Poco M4 Pro

### Android version

Android 13

### Steps to reproduce

Logging into Aegis Vault with vault password logs in, which is okay. But the app is logged in with the backup & export password as well (separate password for backup & export is set in Aegis security settings), which is not intended for vault but backups only. In short, vault logs in with both passwords (two different passwords). Or am I missing something?

### What do you expect to happen?

I expect the Aegis vault to open only with the vault password and biometrics and not the backups password.

### What happens instead?

The Aegis vault logs in with backup & export password.

**Comment by alexbakker** [comment]
This is expected behavior. The separate password for backups is implemented as an extra [password key slot](https://github.com/beemdevelopment/Aegis/blob/master/docs/vault.md#password). When a backup/export is created, the other password key slot is stripped so that only the separate backup password can be used to decrypt the vault file. But in the context of the app, both passwords can decrypt the vault file.
