### ISSUE TITLE
v0.4.3 Error when exporting database

### ISSUE THREAD

**Issue by anotherzen** [beemdevelopment/Aegis#164]
### Problem:
Using the **Export the database** feature, both encrypted and not, returns the error: 
**An error occurred while trying to export the database.**

### Reproduce: 
- Open Aegis
- Click the 3 dots at the top right and select Settings
- Scroll to the bottom and click Export
- Click OK

### My software / hardware
Phone: Pixel 1
OS: Android 10 - July 5th 2019 release.
This is the Beta 5 release of Android 10 which is very close to final release.
Permissions are granted for Storage.

Edit: made issue easier to read

**Comment by alexbakker** [comment]
Thanks for the report.

My first thought was that this could be caused by [the changes](https://developer.android.com/preview/privacy/scoped-storage) that were introduced to the external storage system. However, I'm unable to reproduce this on an emulator with beta 5 of Android 10, even with ``set-isolated-storage`` set to ``on``. The documentation also says that apps targeting API 28 or lower can continue to use the old system for now, so I'm not sure what's going on here.

Unfortunately, we don't have good logging for this particular error yet. Would you be willing to run a debug APK provided by us, reproduce the bug there and capture a log with ADB?

**Comment by anotherzen** [comment]
Sure thing.
Just point me towards the APK and a "how to" for the ADB and i'll give it a spin :)

**Comment by anotherzen** [comment]
This is now working. 
Tested on August 1st release of Android 10.
