### ISSUE TITLE
Add desktop apps

### ISSUE THREAD

**Issue by technozz** [beemdevelopment/Aegis#165]
Add support for desktop apps in Windows, Linux, Chrome apps and Mac

**Comment by alexbakker** [comment]
We don't have plans to port Aegis to other platforms.

**Comment by jidanni** [comment]
Well once #138 is implemented among many apps, you could export your keys from Aegis to some other app running on your desktop.

**Comment by fiorins** [comment]
Something has changed since three years ago about a Windows/MacOS/web app of Aegis ?

**Comment by alexbakker** [comment]
No.

**Comment by PatRiot1337** [comment]
> Well once #138 is implemented among many apps, you could export your keys from Aegis to some other app running on your desktop.

@jidanni Which other apps running on your desktop are there and can you recommend?

**Comment by jidanni** [comment]
(I recall I made an homebrew Perl program from some modules I found; however my desktop is far away at the moment.)

**Comment by PatRiot1337** [comment]
> (I recall I made an homebrew Perl program from some modules I found; however my desktop is far away at the moment.)

Uh, I meant recommendations for MY desktop ;) so an 2FA-App for desktop.

**Comment by jidanni** [comment]
Well mine is just a sloppy Linux command line shell script... I mean Perl script.

**Comment by oviliz** [comment]
Shame we can't get this on iOS though... just changed from Android to an iPhone to find out that I couldn't get Aegis on iOS... :(

**Comment by war59312** [comment]
While no official app exists, you can use the Andriod App on Windows using the Windows Subsystem for Android.

1.) Install Windows Subsystem for Android:  https://www.androidpolice.com/set-up-wsa-windows-11-android-apps/

2.) Enable developer mode and share user folders (and probably want local network access) in Windows Subsystem for Android under Advanced Settings.

3.) Restart Windows Subsystem for Android to enable file sharing: https://www.elevenforum.com/t/restart-windows-subsystem-for-android-wsa-in-windows-11.12301/

4.) Download WSA Sideloader from the Microsoft Store.

5.) Download and install the Aegis APK using WSA Sideloader from the Microsoft Store.

Congrats, Aegis is now installed.

Now you need to get your sweet codes into Aegis.

6.) I found that oddly I could not import the default Aegis file format when exported from my Galaxy S24+ phone. I had to export it as a plain text file. Fun. So yeah export your Aegis codes from your phone as a txt file.

7.) Open the newly installed Amazon Appstore from your Windows start menu and Download and install X-plore .

7.) Use X-plore to copy the Aegis APK to Windows Subsystem for Android. I suggest copying to the Downloads folder to make life easy. Temp anyways, as you can delete the export it when done.

8.) Import your Aegis codes as a plain text file.

Hello, beautiful codes. 💯

**Comment by MaximilianKohler** [comment]
I also think a desktop app is important to have as a backup if something goes wrong with your phone.

Here's what I found:

[Doing it manually](https://www.linux.org/threads/in-depth-tutorial-how-to-set-up-2fa-totp-with-keepassxc-aegis-and-authy.36577/) with **KeepassXC** seems to be the only **portable** option. 

**Tauthy** https://github.com/pwltr/tauthy - recommended at https://github.com/beemdevelopment/Aegis/issues/1004 may be the next best thing. I haven't tried it.

- https://github.com/2fast-team/2fast/ - not portable.
- https://github.com/FireCubeStudios/Protecc - doesn't seem portable.
- https://github.com/flathub/com.belmoussaoui.Authenticator - https://flathub.org/apps/com.belmoussaoui.Authenticator - linux only?
- https://github.com/Levminer/authme-lite - archived.

**Comment by chaoscreater** [comment]
> I also think a desktop app is important to have as a backup if something goes wrong with your phone.
> 
> Here's what I found:
> 
> [Doing it manually](https://www.linux.org/threads/in-depth-tutorial-how-to-set-up-2fa-totp-with-keepassxc-aegis-and-authy.36577/) with **KeepassXC** seems to be the only **portable** option.
> 
> **Tauthy** https://github.com/pwltr/tauthy - recommended at #1004 may be the next best thing. I haven't tried it.
> 
> * https://github.com/2fast-team/2fast/ - not portable.
> * https://github.com/FireCubeStudios/Protecc - doesn't seem portable.
> * https://github.com/flathub/com.belmoussaoui.Authenticator - https://flathub.org/apps/com.belmoussaoui.Authenticator - linux only?
> * https://github.com/Levminer/authme-lite - archived.

I haven't looked into others, but 2fast is technically portable. You can choose to use a webdav server to store your data file and so you could have 2fast running on multiple PCs, pointing to the same webdav file. Alternatively, you can create a local backup of your data file and you can just place that in a Dropbox or OneDrive folder, which is synced. When you switch PC, it'll just be picked up by the sync.

Anyway, I think it's a missed opportunity for the Aegis team to not make a desktop version. I chose Authy because it was the only app that was cross platform. I'm well aware that you can get 2FA Android apps running on Windows using WSL, or even using Android mirroring with scrcpy or something else. But I needed a proper, native Windows app, so that my automation would work. I developed my own Autohotkey script for quickly grabbing the OTP code from Authy Desktop and enter that into any app. I can press certain hotkey combinations (e.g. CTRL+SHIFT+1, CTRL+SHIFT+2....) and it will pick the correct Authy 2FA code and use that. It worked great and the execution is extremely fast, much faster than having to switch to your phone screen (whether manually or whether via emulator or WSL for Android or whatever). It was always less than a second to do that, it's the quickest approach of all. I'm sure I can port this script easily to another desktop app, but the problem is trying to find a good replacement for Authy Desktop.

**Comment by fiorins** [comment]
Why Aegis is in the credits section of Tauthy repo, was it developed by the Aegis team ?

**Comment by alexbakker** [comment]
@fiorins Probably because its design is seemingly inspired by Aegis. Tauthy was not developed by us.

**Comment by MaximilianKohler** [comment]
>Anyway, I think it's a missed opportunity for the Aegis team to not make a desktop version. I chose Authy because it was the only app that was cross platform.

Same. It would be great if Aegis and Tauthy could work together and either merge their projects or make them seamlessly integrable. 

Since I don't create new 2FA accounts often, the KeepassXC manual method works well enough for me for now.

**Comment by Granddave** [comment]
Hi all, I've written a lean CLI utility that uses the encrypted backup file that's exported from Aegis to generate the OTP codes.
Please check it out if it sounds interesting.

https://github.com/Granddave/aegis-rs

**Comment by katastrophe92** [comment]
Let's image this: Aegis for all OS's + Browser extension + cloud sync. Mmmm yeah soo nice😋 That would be the BEST 2FA app.

**Comment by war59312** [comment]
FYI, the Andriod option I posted about probably won't work next year and beyond :(

https://www.tomshardware.com/software/windows/microsoft-is-killing-windows-11s-android-emulator-no-one-will-miss-it

**Comment by ntnguyen1234** [comment]
Sorry, anybody has a solution of importing encrypted JSON on windows? 

I'm really stuck here. I don't really need to use 2FA on desktop, but at least a single backup approach in emergency case which I cannot use android, that's NOT manually import one-by-one like Keepass. And also since Aegis only supports automatic backup with encrypted JSON, I can't have un-encrypted one in my backup storage either.

For example, I will call encrypted one as `encrypted.json`, the one decrypted by [aegis.py](https://github.com/roddhjav/pass-import/blob/master/pass_import/managers/aegis.py) as `decrypted.json` and the plain un-encrypted exported from android app is `plain.json` (this one is not in my backup storage).

- [Tauthy](https://github.com/pwltr/tauthy/issues/95): cannot import `encrypted.json` and when I import `decrypted.json`, nothing happens either. Looks like it needs `plain.json`,
- [2fast](https://github.com/pwltr/tauthy/issues/95): cannot import any JSON files,
- [Protecc](https://github.com/FireCubeStudios/Protecc/issues/8): cannot import any JSON files,
- [aegis-rs](https://github.com/Granddave/aegis-rs): I'm having this [issue here](https://github.com/Granddave/aegis-rs/issues/9),
- Android emulator: I mean... seriously, I need a whole emulator OS to import that file? And I'm not sure about their privacy and security when installing them either.

Honestly, I feel so stuck right now. I'm having the backup file sitting on the desktop, and I don't know what to do with it.

**Comment by scollovati** [comment]
@ntnguyen1234 I've created this Python project https://github.com/scollovati/Aegis-decrypt that allows to decrypt the Aegis vault and export its values in different formats (QR Codes with provisioning URIs included). Also it allows to generate TOTP codes on the fly. Some improvements and new formats are "in progress".

**Comment by Sammy-T** [comment]
If anyone's still interested, I created a desktop app that reads Aegis vault files and generates TOTP codes: https://github.com/Sammy-T/avda
