### ISSUE TITLE
Wear OS support

### ISSUE THREAD

**Issue by MindReKr** [beemdevelopment/Aegis#176]
Any chance of adding Wear OS support?

**Comment by alexbakker** [comment]
There does not appear to be a way to add support for Wear OS without introducing dependencies to proprietary libraries from Google. As such, we do not have plans for Wear OS support.

**Comment by bryanyork** [comment]
@alexbakker What is the concern around adding the required libraries from Google to support Wear OS? Other 2FA apps support the platform. A separate app for people that want this feature could work as well...

**Comment by alexbakker** [comment]
@bryanyork The fact that those libraries are proprietary makes them a bad fit for this project.

**Comment by bryanyork** [comment]
Can you expand on that? Is the issue the license or distributing the app in an open source model?

Android in general has lots of proprietary models and other open source apps use them ..

**Comment by alexbakker** [comment]
The project is licensed under GPL, so bundling a proprietary library would be problematic. But more importantly (speaking for myself here), I believe that proprietary software just has no place in a project like Aegis.

**Comment by bryanyork** [comment]
Ah I guess it's a personal belief here, I guess I can't convince otherwise. I think a closed source add on via a separate app to feature it would solve the issue for distribution, but if you don't want to look at that, I will have to move on to Authenticator Pro. Thanks for your hard work on this project though!

**Comment by SysCrasher** [comment]
@bryanyork I use Wristkey, it can import Aegis plain text exports but you have to do it manually and you must sideload Wristkey. 
https://github.com/4f77616973/Wristkey

**Comment by holocronweaver** [comment]
Lack of Wear OS support pushed me to switch to [Authenticator Pro](https://github.com/jamie-mh/AuthenticatorPro), which is also open source under the GPL. It supports import from Aegis, and is at feature parity for everything I care about (automated encrypted backups, password + biometric encryption at rest, downloadable icon packs, etc.).

My understanding is GPL does not preclude using closed source services like Play Services. As @bryanyork suggests, making proprietary dependencies optional via alternate builds is one path forward for Aegis to support Wear OS while offering an alternative build for those on de-Googled Android builds. Still, for those looking to balance convenience and privacy guarantees, I think a build with limited Play Service integration for Wear OS can make sense, especially if data can be client-side encrypted before transmission through Play Service to the Wear OS app so Google cannot covertly spy within the binary blob. (If Android itself is privacy compromised beyond Play Services, then de-Googling is likely an exercise in futility. Some minimum level of trust is required to operate on Android.)

**Comment by alexbakker** [comment]
I don't think proprietary dependencies are a good fit for Aegis, even in a separate build.

That said, even if we were willing to make an exception here, it wouldn't be easy. The GPL doesn't preclude usage of proprietary services, but it does preclude bundling proprietary code, which is what we would have to do in order to add support for Wear OS.

If Michael and I were the sole copyright owners of Aegis' source code, the license wouldn't stand in the way. We've taken quite a few contributions over the years though, so we're not the sole copyright owners of Aegis' source code and thus we can't change the license to add an exception, without blessing from all past contributors. This is a good thing, in my opinion. It keeps us honest and ensures that the Aegis remains free software. This is the reason why companies make contributors to their open source projects sign a CLA to sign over copyright of all contributions to that company.

**Comment by Percy2Live** [comment]
> Lack of Wear OS support pushed me to switch to [Authenticator Pro](https://github.com/jamie-mh/AuthenticatorPro), which is also open source under the GPL but supports Wear OS. It supports import from Aegis, and is at feature parity for everything I care about (automated encrypted backups, password + biometric encryption at rest, downloadable icon packs, etc.).
> 
> My understanding is GPL does not preclude using closed source services like Play Services. As @bryanyork suggests, making proprietary dependencies optional via alternate builds is one path forward for Aegis to support Wear OS while offering an alternative build for those on de-Googled Android builds. For those looking to balance convenience and privacy guarantees, I think a build with limited Play Service integration for Wear OS can make sense, especially if data can be client-side encrypted before transmission through Play Service to the Wear OS app so Google cannot covertly spy within the binary blob. (If Android itself is privacy compromised beyond Play Services, then de-Googling is likely an exercise in futility. Some minimum level of trust is required to operate on Android.)

Thanks for that insight. Actually made me switch from Aegis to Authenticator pro as the usage of the smartwatch is a great plus in comfort which I don't want to miss when typing in 4-5 codes everyday. I appreciate all considerations in regards of the security of the application. But lastly I believe it needs to be taken into account that we're just talking about the 2nd factor here which is useless on its own. Not to say that it has been proven in a lot of studies that a lack of convenience causes people to search for an easier and unsafer approach (like disabling 2FA). That said, I'd rather use a 99,9% secure approach which is convenient than a 100% approach which might make me skip 2FA for my everyday applications.

**Comment by holocronweaver** [comment]
@alexbakker Thanks for the thoughtful response! Could you elaborate on the specific proprietary code that would need to be bundled:
> preclude bundling proprietary code

My understanding is you would need to use the WearOS SDK and could avoid directly using Play services, which should be OK for GPL without adding exceptions since it is both a library and an integral part of the OS (similar to Windows closed libraries that GPL apps use without additional exceptions), but perhaps I'm missing a technical wrinkle.

**Comment by martinhoyer** [comment]
Sorry for necroing a closed issue, just wanted to mention that it's not "either/or" when it comes to proprietary. [Stratum](https://stratumauth.com/download) does fully floss builds obtainable through F-droid repos or gh releases(Obtainium) with only gplay builds supporting wearos, including proprietary components. I can 100% understand not making gplay releases not free, but can imagine having a opt-in "module" or a separate Aegis(non-free) app. 

I'm also thinking some things could be walked around by sideloading apks to wearos via adb, but that doesn't sound very practical, especially for updates.
