### ISSUE TITLE
Exiting the app brings me to the "Unlock the Vault" screen again

### ISSUE THREAD

**Issue by thebeardedchild** [beemdevelopment/Aegis#180]
When I open the app, I can unlock the vault (with password of FP like normal) and use the app/view codes. All normal.

BUT then when I go to leave the app (pressing Android back key), I'm brought to the "Unlock the Vault" screen again, and can't exit the app until I enter PW or use FP.

Not sure if this is intended behavior, but it just seems weird.

**Comment by xopez** [comment]
Just intalled it for the first time and can confirm this.

**Comment by michaelschattgen** [comment]
Hi, thanks for your contributions. What you are describing reported in #151 and fixed by #144.  We currently run an internal beta build and are preparing for a new release. However, even after this fix Aegis doesn't close with the back button. It just doesn't close anymore after entering your password or fingerprint, that's another bug. I've made a new issue (#182) for that which you can keep an eye on.

I will close this issue for now.
