### ISSUE TITLE
Support Device Credentials 

### ISSUE THREAD

**Issue by bishtawi** [beemdevelopment/Aegis#212]
Coming from AndOTP, one feature that I really liked was that the app's authentication supported the device's credentials. This meant that I didnt have to memorize a separate password to access my one time codes. I simply enter the password I had set on the Android device itself.

Any chance to support this?

**Comment by alexbakker** [comment]
When you select the "Device Credentials" option in andOTP, your token secrets will be encrypted with an Android KeyStore key **exclusively**. No other key or password is able to decrypt your tokens. The Android Keystore is [forgetful](https://doridori.github.io/android-security-the-forgetful-keystore/#the-problem), so this strategy can result in nasty surprises for users. This is why Aegis will always require a password in addition to any Android KeyStore backed authentication methods (like fingerprint).

That said, I see 2 ways to support device credentials in Aegis:
1. __Plain text__: Simply prompt the user for device credentials on app startup.
2. __Encrypted__: Add a new slot type for an Android KeyStore key that requires unlocking the Keyguard to use it. This means that the vault can stay encrypted and that it can be unlocked by providing your device credentials. The important difference between this and our fingerprint authentication option, is that access to the key is not governed by the TEE, but by the operating system. This means that root can always use the key, regardless of whether you've entered your device credentials. Also keep in mind that setting a password would still be required here.

Which is of the two options is the closest to what you have in mind?

In general, I prefer giving users two simple options: no security or great security. Offering alternative 'security' options (like prompting for a PIN) in between those two extremes is only going to confuse non-technical users, by making them think they're getting real security. There are a number of apps that have taken the whole flexible security thing too far and I think we should be cautious to not fall into the same trap.

Long story short, I'm not a big fan of either of the two options, but I'm curious to hear what others think about this.

**Comment by bishtawi** [comment]
Option 2 is probably the closest to what I would want. Option 1 is pretty much useless and is basically pretend security as the database is plaintext. I definitely agree that giving users a false sense of security is not a good idea at all.

**Comment by chiraag-nataraj** [comment]
I think the second one would be iffy as an option. I think the strength of Aegis is that it puts security first, and the issue with Option 2 is that root (aka the system) would always be able to unlock the database if it wished to do so. Contrast this with the current situation, where root would not be able to unlock the database even if it wanted to.

If I understand @alexbakker correctly, this is a design flaw ("feature") of the way the keystore works. If there is no way we can work around that (and I don't think there is), I'd prefer not adding this feature.

**Comment by claudioweiler** [comment]
Just to understand:
- Option 2 is use the hardware backed keystore to protect password used to encrypt database?

If yes, then, about forgetfull keystore:
- If I change my device security settings, than I just need to re-enter my password?

About security, i don't understand the issue here. Are you concerned about android itself or about rooted devices?

**Comment by alexbakker** [comment]
I'm mostly concerned about adding additional ways of securing the vault that are inferior to what we have right now.

**Comment by claudioweiler** [comment]
Why encryption with keys that can't be accessed are inferior?

**Comment by alexbakker** [comment]
As explained in my comment, the difference is in who is governing access to usage of the key. With Keyguard, it's always the operating system, making it less secure than what we currently have.

**Comment by claudioweiler** [comment]
Sorry been so pedantic, but I can't see why it should be less secure.

I search a lot about any security issues about hardware backed keystore, but find none except for rooted devices. This is even used for bank apps. Can you share any related issues that you find for background?

**Comment by alexbakker** [comment]
> I search a lot about any security issues about hardware backed keystore, but find none except for rooted devices

It's not just rooted devices, any way of acquiring root (through an exploit, for example) would allow access to usage of Android Keystore keys. We currently require biometric authentication for usage of Android Keystore keys. So on devices that properly implement biometric authentication, even root can't use the key without the user authenticating first. Now, which of the two offers more security, in your opinion?

Note that I'm not trying to argue that relying on Keyguard for governing access to the Android Keystore is horribly weak or a bad idea. It's just that we have better authentication now, and it would be a bad idea to add Keyguard as another option and make users choose between them.

**Comment by michaelschattgen** [comment]
Closing this issue as we unfortunately don't have plans to implement this.

**Comment by alexbakker** [comment]
> Would you mind elaborating on this forgetfulness? the article linked has many comments that the APIs it discusses are now deprecated. Specifically, I am curious about current behaviour.

It varies wildly across devices and manufacturers. It has stabilized a lot over the last couple of years, but we still occasionally get reports from users alleging that their Keystore was wiped spontaneously.

Aegis also makes use of [a feature](https://developer.android.com/reference/android/security/keystore/KeyGenParameterSpec.Builder.html#setUserAuthenticationRequired(boolean)) that intentionally wipes keys with that option enabled from the Keystore if changes to security settings of the device are made. This is an important security feature, but that means you need a different primary way (a password, in Aegis' case) to decrypt the vault.

> Is there a problem if i change within each type? for example: a pattern is currently set, and i change it to a different pattern. or a pin is currently set, and i change it to a different pin.

I don't think that triggers a Keystore wipe, but I can't find any documentation that makes this explicit, so I'd recommend testing this to double check.

> It looks like MS Authenticator uses the device credentials and changing the locking "code" (pattern, pin, etc.) does not cause any problems although I haven't changed the type of locking method.

That means they don't use ``setUserAuthenticationRequired(true)`` like Aegis does. In fact, Microsoft Authenticator just stores everything in plain text, so their device credential prompt is mostly theater.

**Comment by corobin** [comment]
revisiting this - since andOTP is now unmaintained - is there any possibility of getting device credentials support in aegis just with a big fat warning about the chance of data-loss?

I have been using andOTP with device credentials without a problem, changing the device passcode without changing the type (i.e. changing one PIN to another PIN, not changing PIN to pattern) does not erase the andotp keystore. of course, you'd be more familiar than me if andOTP is actually encrypting using device credentials.

I do not consider the authenticator app to be the sole store for my 2fa codes - i have backup codes for recovery and will not lose access even if aegis loses everything.

the on-device TOTP codes are meant to be hard to recover, you're not supposed to be able to take them off the device easily. if TOTP codes are easily taken off-device it defeats the whole point of proving physical possession of *that* device. using android's device credentials ties the TOTP database closer to that phone.

ideally you would remove any backup functionality altogether but that ship probably sailed.

**Comment by Lanchon** [comment]
> 2\. **Encrypted**: Add a new slot type for an Android KeyStore key that requires unlocking the Keyguard to use it. This means that the vault can stay encrypted and that it can be unlocked by providing your device credentials. The important difference between this and our fingerprint authentication option, is that access to the key is not governed by the TEE, but by the operating system. This means that root can always use the key, regardless of whether you've entered your device credentials. Also keep in mind that setting a password would still be required here.

sorry, either i don't understand you or i find this very hard to believe.

i don't know the android keystore code base, but common sense dictates that it is probably well designed.

this means that if you store a secret in the keystore protected by the device creds, and contrary to what you say here, neither root nor any userland component nor the android kernel can access it without you providing the device creds (pin/pattern). if android is well designed, the application processor simply does not cache the creds, and the hardware keystore will not release the secret without them. so the only thing the app processor can do is to ask the user for the creds whenever it needs them and hope the user releases them.

> This means that root can always use the key

specifically this would be false. that's the whole reason for the hardware backing store thing to exist anyway, IMHO.

### threat models

of course if you corrupt android's userland or kernel, you can make it memorize the creds the next time the user types them in, if ever. but under this threat model, nothing tells me that the same trick couldn't be done with the fingerprint sensor: just use the next unlock scan to unlock the vault instead of the phone.

> I'm mostly concerned about adding additional ways of securing the vault that are inferior to what we have right now.

security solutions can't be meaningfully compared without threat models. i am curious as to which threat models you had in mind when you wrote this.

but here is a counter example: within the following attack model, if you compare the security of storing the key to the vault in the keystore protected by biometrics vs by the device creds, the device creds solution is demonstrably superior. (this again assumes a reasonable implementation of android, as said above.)

threat model: gov agents detain you and confiscate your phone. they can forcefully use your biometrics but they will not forcefully extort secrets out of you. your phone is locked but is not locked down (very reasonable). and either your phone is protected by fingerprint, or they have some application processor exploit that can bypass the lockscreen (if the phone is not locked down). then:
- if the vault is protected by fingerprint: the vault is compromised.
- if the vault is protected by device creds: the vault is safe, as the backing store will not release the key without the user revealing the creds.

note that you recognize that the phone has been breached in either case, and you cease to trust it as a trusted agent of yours. consequently, you will not provide your creds to the phone ever again and will discard it instead. you know that backups of the vault are safe elsewhere, and encrypted with your strong passphrase.

so clearly, in the scenario above (which is very reasonable) the vault protected by device creds is the superior solution, not the inferior one as you stated earlier.

### caveat

of course this all falls down if you have proof that android caches the device creds in the app processor. again, i find this very hard to believe, but would love to be proven wrong if i am. as someone said: it's not what you don't know that hurts you the most, but what you think you know and are wrong about.

**Comment by Lanchon** [comment]
hi @alexbakker 

i've challenged your earlier assertions a long while back, but got no response.

> The Android Keystore is [forgetful](https://doridori.github.io/android-security-the-forgetful-keystore/#the-problem), so this strategy can result in nasty surprises for users.

i don't understand what the big deal is here: users unlock the vault with their passphrase, but they optionally want to cache the key derived from the passphrase with the Android Keystore. if the Android Keystore forgets, you reenter the passphrase. 

so what is the big deal? is it a UI problem? are you afraid of people forgetting their own secure passphrase? which is why you force them to use inferior security because they can't type such a long passphrase every time they need to log in to github? well, some people forgetting their passphrase is not a valid reason to impose poorer security on everyone else.

several apps deal with this issue by periodically asking for the passphrase. but you are not required to deal with forgetful users: just make you app functional for those who use it responsibly.

by not doing this you are negating the security advantages provided by a TPM.

----

# for everyone else...

it seems unlikely that Aegis will ever become usable and secure for those unwilling to consider biometrics as secure and unable to type a huge passphrase every time.

please provide secure alternatives that will unlock with Device Credentials. thanks!

**Comment by bam80** [comment]
> The Android Keystore is [forgetful](https://doridori.github.io/android-security-the-forgetful-keystore/#the-problem), so this strategy can result in nasty surprises for users.

This seems have changed since then. From the same article:
> Use the KeyStore in L-6-23+ in one the above configurations which seem to be “safe” from key loss and have a relative degree of confidence your keys are not going anywhere.

**Comment by Lanchon** [comment]
it is still relevant that the keystore being forgetful is not a blocker for using it as explained in my previous message.

**Comment by Ajedi32** [comment]
In my opinion, the overall architectural design of Aegis' security model is a bit off right now. The default settings put too much focus on guarding access to the OTP codes as if they were passwords. They're not.  In fact, it would be more or less totally fine if anyone in physical possession of my phone could see my 2FA codes; that wouldn't compromise my security model at all.

The point of 2FA is to allow me to provide proof of "something I have" to the party I'm authenticating to in addition to the "something I know" I've already provided by sending my password (stored in my password manager, unlocked via a master password). Requiring a password (something I know) to access 2FA codes is therefore redundant and unnecessary; I've already provided a password to the website (or a WebAuthn response, etc).

You could just turn off encryption entirely, except that's also not a good idea because in order to guarantee the integrity of the 2nd factor the OTP seed database itself *must* be as strongly guarded as possible. Someone physically present accessing my OTP codes is no big deal, but if they can *export* the seed database without my knowledge, that would be very bad. Therefore, the database needs to be encrypted, ideally with a key that can not ever leave my device (i.e. in the TPM).

Aegis has a Biometric Unlock feature which is very close to doing what I want here, except that it does not allow using my lock screen code as a back up, only my fingerprint, which is inconvenient if for whatever reason my fingerprints are not readable (wet, wearing gloves, etc). I could set an encryption key that's the same as my device unlock code, but 6 numerical digits is not very resistant to brute force without the aid of a TPM like my device relies on to secure the lock screen. It does look like there's a "Separate password for backup & export" box you can toggle which would allow me to set a stronger key for exports, but even with that on the primary encryption key would still be weak and presumably (correct me if I'm wrong) not stored in the TPM.

What I'd like to do is have the TPM-protected device credentials be the primary layer of defense for the encrypted seed database, with a separate, long, brute-force-resistant recovery key protecting any exports of the database. Right now this is only *sort of* doable, whereas I'd argue it should be not only possible, but actually the default flow most users should use.

**Comment by Ajedi32** [comment]
Looking at the documentation a bit, I think all that's technically needed here is to include [KeyProperties.AUTH_DEVICE_CREDENTIAL](https://developer.android.com/reference/android/security/keystore/KeyProperties#AUTH_DEVICE_CREDENTIAL) when calling [setUserAuthenticationParameters()](https://developer.android.com/reference/android/security/keystore/KeyGenParameterSpec.Builder#setUserAuthenticationParameters(int,%20int)).

That wouldn't solve the larger UX flow issues but it would at least make it *possible* to get what I'm looking for by allowing the database to be decrypted with the device PIN (so the only time you'd need to actually use the database password would be when restoring from backup, so you could set like a 32-character long password and use it as a recovery code).

**Comment by Ajedi32** [comment]
> all that's technically needed here is to include [KeyProperties.AUTH_DEVICE_CREDENTIAL](https://developer.android.com/reference/android/security/keystore/KeyProperties#AUTH_DEVICE_CREDENTIAL) when calling [setUserAuthenticationParameters()](https://developer.android.com/reference/android/security/keystore/KeyGenParameterSpec.Builder#setUserAuthenticationParameters(int,%20int))

Submitted #1798 to track this

**Comment by Lanchon** [comment]
@Ajedi32 2FA is a PoS when forced upon users the way the enshittified internet does. the "something I know" + "something I have" model was completely broken by the corp "geniuses" everywhere: 2FA is now used as a password recovery method.

thus, your attack model does not generalize. for mine, i can foresee a future in which someone forcefully uses my finger to unlock my phone. yet they must absolutely *not* be able to get from my phone to other places without "something I know". the reason is simple: in many western countries, compelling the use of your finger is *legal* but compelling the compromise of your secrets (eg, by torture) is not. (and no, i am not saying that countries abide by their own laws -they clearly never will- but it does introduce friction, which is what i need.)

> the database needs to be encrypted, ideally with a key that can not ever leave my device

that is also not compatible with my use case, which requires the database be backed up and the backups being usable.

without thinking much on it, it seems the circuit should be simple:

- passphrase *==hash==>* key
- cache key in TPM, if user chooses:
  - make TPM ask for secret to release key, if user chooses:
    - allow any unlock mechanism
    - force non-biometric unlock mechanisms only *<=== this is my request that the dev has been ignoring*
- to unlock give option of TPM query or full passphrase fallback
  - this takes care of potential TPM forgetfulness
  - and optionally:
    - force user to enter full passphrase once in a while, **only if user chooses**
      - this takes care of potential user forgetfulness
      - force re-passphrasing the vault if user cannot provide the correct passphrase
        - assumes user and TPM do not both forget at same time

**Comment by Ajedi32** [comment]
@Lanchon I'm not arguing against options if your personal threat model differs from what's typical, I'm just saying Aegis' current default UX seems to treat 2FA codes as something they weren't designed to be ("something you know"), and that the user experience for the thing 2FA codes *were* designed to be ("something you have") requires you to fight the UI a bit to configure and lacks one feature which in my mind is necessary to make it work smoothly (device PIN-based unlock).

> my use case, which requires the database be backed up 

To be clear, I agree backups should be part of the default experience. It compromises the security model of 2FA a *tiny bit*, but the UX of losing all your creds when you change phones is so absolutely *awful* that I think the trade-off is necessary.

> my request that the dev has been ignoring

Just a reminder: Aegis is a free, open source application. The developers owe us nothing. I'm only commenting to share what I see as a potential way to improve to the application. I'd obviously love it if someone were to implement my suggestions, but if nobody feels like doing that they're totally free to ignore me. :)

**Comment by Lanchon** [comment]
> if your personal threat model differs from what's typical

this is a loaded argument.

> Just a reminder: Aegis is a free, open source application. The developers owe us nothing.

i am FLOSS developer. this is a change of subject, an obvious fact, and completely uncalled for. i have [challenged](https://github.com/beemdevelopment/Aegis/issues/212#issuecomment-2399047214) what the dev said earlier and got no response. developing FLOSS does not shield you from comments or even criticism. you can be a FLOSS dev, and at the same time be wrong; i know that well myself. i have challenged the dev, not roasted him for not doing what i want; there is a difference.

however, i would prefer the dev saying "i don't want to develop that feature because i don't like it; also i won't merge it if someone else PRs it" rather than saying the that feature cannot be safely implemented due to design issues of the android OS, without providing proof/source of such issues.

i am not convinced the dev is right. and posting this here is not trolling: it can help the dev update their beliefs, it can help others that come here to learn more (like i did), and it can help me understand why i am wrong if that is the case. it all hinges on somebody addressing my concerns, which has not happened.

**Comment by corobin** [comment]
> i can foresee a future in which someone forcefully uses my finger to unlock my phone. yet they must absolutely _not_ be able to get from my phone to other places without "something I know". the reason is simple: in many western countries, compelling the use of your finger is _legal_ but compelling the compromise of your secrets (eg, by torture) is not. (and no, i am not saying that countries abide by their own laws -they clearly never will- but it does introduce friction, which is what i need.)

aren't you placing the safeguard on the wrong place here? the countermeasure to the attack you've described is to not use biometrics at all. rather than letting the attacker in (which opens up massively more attack surface) and then counting *entirely* on one specific app to thwart the attack.

this app is currently *less* secure because the only device credential that it supports is biometrics, which you've correctly identified as weak.

>     * force non-biometric unlock mechanisms only _<=== this is my request that the dev has been ignoring_

If the app supports full device credentials, and you only have non-biometric device credentials, this would be equivalent to forcing non-biometric unlock.

it seems to me like we are all basically asking for the same thing.

> however, i would prefer the dev saying "i don't want to develop that feature because i don't like it; also i won't merge it if someone else PRs it" rather than saying the that feature cannot be safely implemented due to design issues of the android OS, without providing proof/source of such issues.

I agree, if the dev just plain doesn't feel like it, that's within their power and everyone can act accordingly.

**Comment by Lanchon** [comment]
> aren't you placing the safeguard on the wrong place here? the countermeasure to the attack you've described is to not use biometrics at all.

that is exactly my point. i do not want to use biometrics with this app and i do not use them.

> this app is currently less secure because the only device credential that it supports is biometrics

exactly. this has been my point all along.

> If the app supports full device credentials, and you only have non-biometric device credentials, this would be equivalent to forcing non-biometric unlock.

true. but my device does use bios to unlock though, and i want it that way. as i said, my threat model is: they *can* get to my phone, but they *cannot* get from there to other places. phone unlocks with bios, vault should not.

my setup actually improves security: if i have to enter my pin/pattern all the time to unlock my phone in regular use, it is simpler for an adversary to obtain it (eg, just watch me in security footage at the airport). also, i might be required under some circumstances to unlock my phone (eg, when entering some countries), but i do not want to give away my pin/pattern (and my vault) in that situation.

my point has also been that denying users the ability to use a TPM forces the users to choose a weak vault passphrase because few would want to type a 30 character passphrase every time they are stupidly forced to re-sign in into stupid github reply to a comment. (github could force a higher auth for commits, releases, uploads, etc, to protect other users. but they are incredibly stupid and they treat any stupid action as critical. but what can you expect out of microsoft.)

> it seems to me like we are all basically asking for the same thing.

i think i never said otherwise. or did i reply negatively to anything you said before on here and i do not remember? maybe you confused me with some other poster?
