### ISSUE TITLE
Is there a security benefit in using the app based encryption when the phone is already using full disk encryption?

### ISSUE THREAD

**Issue by e00E** [beemdevelopment/Aegis#213]
Some arguments I could think of:

1. A user could accidentally copy the vault to an unencrypted location for example when performing a back up.
2. The operating system might not sufficiently prevent malicious apps from accessing other app's data. Counterpoint: If the operating system has problems like this then even with app based encryption the malicious app might be able to record the keyboard or read Aegis' memory.
3. The phone might get lost while it is running and would be in an unlocked state from the point of view of full disk encryption whereas Aegis immediately locks the vault after use.
4. The full disk encryption might use weaker algorithms than the app based encryption.

This question might be relevant for other people so it could be added to the documentation.

**Comment by chiraag-nataraj** [comment]
Yeah, as far as I'm concerned, the primary benefit is encrypted backups without having to do anything extra. I do think the last point is also somewhat valid, although admittedly mainly for older phones.

Fundamentally, having the data encrypted at rest _even when the whole OS is encrypted_ is useful when you don't trust the platform to do the right thing. Additionally, many people _don't_ use FDE, so for them, the vault would be completely unprotected, even when the phone is turned off, and I don't know if there's a way to detect if FDE has been turned on.

**Comment by alexbakker** [comment]
Hmm, looks like we've forgotten to answer this old question.

Briefly: full disk encryption is useful, but only helps if someone gets a hold of your device while it is turned off. When the device is turned on, you enter your PIN/password once to decrypt the master key. From that point on encryption/decryption is handled transparently and the filesystem is exposed to the operating system as if all files are in plain text. Aegis also has its own encryption, so that a vulnerability in the operating system does not necessarily also lead to a compromise of Aegis' vault. It also makes backing up the vault easier/safer, since it's already encrypted anyway. Password managers and other applications that handle sensitive data do the same thing for the same reasons. It's just one piece in a defense in depth strategy.
