### ISSUE TITLE
Fingerprint not available

### ISSUE THREAD

**Issue by kelvinwl** [beemdevelopment/Aegis#233]
###### Info

* __Version__: 1.0.2
* __Source__: Google Play
* __Vault encrypted:__ Yes
* __Android version and ROM:__ 6.0.1

###### Steps to reproduce

Just open settings and scroll down to "fingerprint".

###### What do you expect to happen?

Be able to enable fingerprint option.

###### What happens instead?

Nothing. The option is grayed.

**Comment by alexbakker** [comment]
Do you have fingerprints enrolled on your device?

**Comment by kelvinwl** [comment]
Yes, I do. I unlock the phone with my fingerprint.

**Comment by alexbakker** [comment]
Hmm. I remember some devices with early (Android M) fingerprint sensor support not supporting the standard API for it. Which phone model do you have? (Note to self: add that to the issue template)

**Comment by kelvinwl** [comment]
It is the Samsung S5 mini dual sim (G800H). If you need more information let me know. Thanks!

**Comment by alexbakker** [comment]
Ah, as I suspected. Samsung phones that had fingerprint sensors before Android 6 was released typically do not support Android's standard fingerprint API and rely on the [Samsung Pass SDK](https://developer.samsung.com/release-note/view.do?v=R000000009) instead. We are not able to add support for those devices. Sorry.

Here's what's happening in Aegis: The check for fingerprint hardware passes, but the check for enrolled fingerprints does not. That's why you see that option grayed out in the settings.
