### ISSUE TITLE
Add Support for SafeNet MobilePASS OTP

### ISSUE THREAD

**Issue by tERyceNzAchE** [beemdevelopment/Aegis#250]
Add support for SafeNet MobilePASS OTP (software token).

**Comment by yoshimo** [comment]
https://github.com/ars3niy/openpass may help you out

**Comment by michaelschattgen** [comment]
Closing this issue as we don't have plans to implement this. If someone wants to take responsibility of implementing this, feel free to restart this discussion.

**Comment by JordanPlayz158** [comment]
I am thinking of implementing SafeNet MobilePASS before preceding, I'd like to know if we still would be open to supporting it if I do the work to implement it into Aegis

**Comment by alexbakker** [comment]
Thanks for offering to implement this!

We're usually a bit hesitant to support proprietary protocols like this one, because there's usually little to no documenation about them, apart from some reverse engineering efforts. In this case it seems like we're dealing with yet another custom spin of HOTP though, so it's probably not as big of a concern.

There are still a couple of things that are unclear to me:
- How does the setup process work? Do users scan a QR code? Are there other ways? Does the setup process require an internet connection?
- Which websites/services implement this protocol for 2FA? Are there any we can use to verify our implementation against? Or is there a server implementation that we can deploy ourselves perhaps?

**Comment by yoshimo** [comment]
In my case i got an e-mail with a link to the safenet enrollment portal of my company.
This page shows a special link that the official app can open and an alternative string that you can paste in the app to create a new entry.
I haven't captured the traffic but it seems like internet for the initial setup is required. My Token wasn't registered on the company server as active when i was offline which probably was the reason why it initially didn't work and need to be reset.
In my case it is connected to A citrix Workspace and a MS 365 instance.
It is sold by Thales as a product and also available on the citrix marketplace.

**Comment by alexbakker** [comment]
If an internet connection is required in the app for initial setup, we can't add support for this to Aegis, because we don't request the internet permission.

**Comment by yoshimo** [comment]
This is a rather weak argument and is easily changed to support  more Auth mechanisms. 
Also you can still import keys from the original app that setup the token.

**Comment by alexbakker** [comment]
> This is a rather weak argument and is easily changed to support more Auth mechanisms.

Of course it would be easy to request the internet permission. We're not going to, though.

> Also you can still import keys from the original app that setup the token.

Sure, if there are other ways to set up tokens for this, that'd be fine.

**Comment by JordanPlayz158** [comment]
Yeah, I can look into making an importer then

**Comment by walla5e** [comment]
@JordanPlayz158 have you made any progress on this?
Best Regards

**Comment by JordanPlayz158** [comment]
I apologize, I should have kept posted, I have been working on other projects and won't be looking into implementing this anymore
