### ISSUE TITLE
Allow creation of Czech translation

### ISSUE THREAD

**Issue by R3gi** [beemdevelopment/Aegis#253]
Hi, could you please add Czech language to the list of target languages at Crowdin?
I would like to create Czech localization. Thanks 😉

**Comment by michaelschattgen** [comment]
We've added Czech to our target languages on Crowdin. Feel free to translate.

Thanks!

**Comment by orangesunny** [comment]
Hi there, and thanks to both of you!

I walked through all the strings today, made some corrections to make the app sound more Czech than a strict translation. I also filled the missing pieces. Can we include it in the following release?

Also, I have a question: there are two _strings.xml_ files in Crowdin that look like duplicates. Can you clarify that? I don’t want to check string-by-string one more time. Thank you and kudos for amazing app.

**Comment by R3gi** [comment]
@orangesunny Hi, thanks for joining :-) I've commented a few of your translations, please check them.

It would be great to pack new translations to every release automatically. I think Crowdin has some API for that…

**Comment by orangesunny** [comment]
@R3gi Thanks for all your comments, I made corrections for better thanks to them.

It depends on the setup of the translation project, so it is kinda tricky. Yes, there is API and GitHub integration, too. I updated Aegis to today’s version from Play Store with no changes. :(
That might also be due to the duplicated *strings.xml* file. I believe that the one in *master* is the right one as we have most of the app already translated. Can @michaelschattgen bring some light on this/clear it in Crowdin, please?

**Comment by michaelschattgen** [comment]
Thank you very much for updating the translations for us. We are both very new to Crowdin and I accidentally uploaded a strings.xml file from a different branch than master. I removed all the duplicate strings.xml files and it should be up to date now.

The strings.xml file you now see in Crowdin is the most recent and the correct one. Hit me up whenever something is unclear or missing!

**Comment by R3gi** [comment]
@michaelschattgen Thanks! If you need help with Crowdin's project settings, just DM me 😉 I also recommend Crowdin's documentation, it's quite good 👍

**Comment by michaelschattgen** [comment]
Thanks, I will keep it in mind!

**Comment by orangesunny** [comment]
Thank you for being open and creating such a good app. Also thanks for a cleanup, we will check the missing strings continuously.

About the translation system, I can also help a little. I am a member of the core team of Weblate, the open source localization platform. If you want, we can move Aegis there and attract more translators from the open source community. 
https://hosted.weblate.org/projects/ Yes, project like openSUSE and Fedora have their own instances.
We can set up the integration and never have to manage files again. The only thing for that is to add a Weblate user to the repo. https://github.com/weblate

Another place where we can polish Czech translation is plurals:
- https://docs.weblate.org/en/weblate-3.10.3/user/translating.html#plurals
- https://support.crowdin.com/icu-message-syntax/#plural

@michaelschattgen @R3gi 
By the way, who of you is going to FOSDEM? :)

**Comment by R3gi** [comment]
@orangesunny Great suggestion, but personally I would keep Crowdin.
It has simply the best UX and tools for translators, proofreaders and managers. As far I know, they also offer free projects for open source apps upon request, which is great!
I know Weblate, it's a good software, but to be honest, it will still require a lot of work and many years before it could be at least half as good as Crowdin. Aegis needs to rise today, not tomorrow, and the project management has to be simple as possible, so I would definitely keep current solution. No offense, just sayin' 😉

Btw. we are a bit off-topic in this thread.

**Comment by orangesunny** [comment]
Yes, I offered my help with translation management to boost Aegis' popularity, community, and development. Well, that’s the magic of the competition that we can push each other forward. :) Our users and customers say the same things as you, in the opposite direction. If you would save a few minutes and write to me what you feel missing and we can do better in Weblate when comparing with Crowdin, send me an email, I would be very happy.

Yes, I permitted myself to go partially away from the topic as the issue is closed and all participants are related to the offtopic. Sorry :)

**Comment by R3gi** [comment]
@orangesunny Sure, I've send you feedback via mail :-)

**Comment by orangesunny** [comment]
Thank you so much, got it, and I am looking forward to our beer!
And you were right! Vivaldi is still using Weblate version 2.10, which was released on Dec 15th 2016 :( I will write them and tell them to update. Check out https://hosted.weblate.org/ too
@R3gi @michaelschattgen What about FOSDEM?

Now I promise to stop this off-topic.
