### ISSUE TITLE
Add import from LastPass Authenticator

### ISSUE THREAD

**Issue by vnord** [beemdevelopment/Aegis#262]
I'm very sorry for the incorrect title of the last issue! It's been a long day, and the part of the copy-paste where you change the relevant word escaped me.
As I wrote there, there should be a SQL database lying around somewhere, but I can't find it. If I can find it and figure out how it works, perhaps I could attempt to implement this.

**Comment by alexbakker** [comment]
Ah! No worries. Thanks for resubmitting it.

**Comment by lanesawyer** [comment]
This would be a fantastic feature.

Currently there's no way to get the backup or the TOTP from LastPass Authenticator, so I'm going to have to manually re-add all my accounts before I can start using Aegis... 😔

**Comment by budde25** [comment]
So after looking into this a bit it looks like LastPass Authenticator encrypts all the tokens with AES encryption using a key named "DefinitelyNotAnImportantFile" and another one using the android keystore. The first one shouldn't be hard to use since its just a file to read but I have no idea if its possible to get the second one from the android keystore.

**Comment by michaelschattgen** [comment]
Closing this issue as we don't have plans to implement this. If someone wants to take responsibility of implementing this, feel free to restart this discussion.

**Comment by 3xploiton3** [comment]
hmmm i looking for this feature, all my account stuck in lastpass authenticator, 😔

**Comment by alexbakker** [comment]
@3xploiton3 Let us know if you'd like to give implementing this a shot.

**Comment by vnord** [comment]
I found a database file at /data/user/0/com.lastpass.authenticator/databases/databases using SD maid with root. The account details were not encrypted, but the tokens were. When I get time I'll look into it some more. I'm guessing the key might be the master password and some salt - any leads from anyone with more experience on how to decrypt the tokens?

**Comment by mathieujobin** [comment]
@budde25 @vnord please let us know if you find out more. A lot of people would like to switch away from LastPass now.
and being able to import our data into Aegis would be super awesome.

**Comment by bzy39** [comment]
found this.
https://blog.unauthorizedaccess.nl/2021/03/07/export-totps-from-lastpass-authenticator.html
https://github.com/dmaasland/lastpass-authenticator-export

**Comment by mathieujobin** [comment]
@bzy39 cool stuff ! personally, I am fully migrated but I did it manually
resetting up my 2FA everywhere

**Comment by bzy39** [comment]
mine just migrated today, after some search found that, just need to change the exported format.

**Comment by thany** [comment]
@michaelschattgen 
> Closing this issue as we don't have plans to implement this. 

Please reopen this issue. Not having plans isn't normally a reason for closing the issue, because the issue still exists, and isn't resolved, and hasn't vanished. In other words, if you don't currently have plans to implement, please make those plans.

@bzy39 
If I understand that script correctly (and mind you, I don't speak python), I have to have a LastPass account and backup my vault to it, right? Well if that, therein lies my problem: and I don't have or want a LastPass account... And I prefer not to create one for the sole purpose of using it as an intermediate storage for my vault. I just don't trust them with it, it's that simple.

So, do you happen to know of an alternate method to getting that magical export file without first pushing it to lastpass?

**Comment by alexbakker** [comment]
> Not having plans isn't normally a reason for closing the issue

It actually is. GitHub even has a dedicated button for it.

![image](https://user-images.githubusercontent.com/2387841/172593947-47f21ae8-a37c-43ac-8a77-e80231f0b1bb.png)

**Comment by thany** [comment]
@alexbakker Hm, didn't know. But regardless, the wish for this feature remains 😊

**Comment by tghw** [comment]
LastPass Authenticator now has an Export to JSON feature. I don't know enough about the various formats, but it seems this should make this ticket relatively easy.

**Comment by tghw** [comment]
As I'd hoped, it's quite easy to convert between the two. Feel free to use the following script: https://gist.github.com/tghw/27a4b3a237e6f62a8bb9a46670e59f61

To run it, download the script and run:
`python lp_aegis_convert.py path/to/lastpass_auth_export.json`

It will convert the LastPass Authenticator entries to the Aegis JSON format. Then, go to Import/Export -> Import in Aegis and use the Aegis file type.

You will need to transfer the files off and back onto your phone to make this work, something like Dropbox will make that easy.

And to the Aegis devs: Please feel free to use the above script as a template to write a LastPass Authenticator import/convert class. Clearly there is demand for it.

**Comment by vkice** [comment]
> As I'd hoped, it's quite easy to convert between the two. Feel free to use the following script: https://gist.github.com/tghw/27a4b3a237e6f62a8bb9a46670e59f61
> 
> To run it, download the script and run: `python lp_aegis_convert.py path/to/lastpass_auth_export.json`
> 
> It will convert the LastPass Authenticator entries to the Aegis JSON format. Then, go to Import/Export -> Import in Aegis and use the Aegis file type.
> 
> You will need to transfer the files off and back onto your phone to make this work, something like Dropbox will make that easy.
> 
> And to the Aegis devs: Please feel free to use the above script as a template to write a LastPass Authenticator import/convert class. Clearly there is demand for it.

Very nice script that worked perfectly.

Only change I made for my own sanity was L19 where I changed the arg from issuerName to userName, otherwise it was just that company's name twice without my specific accounts name. Much easier to know what account I was looking for if there was multiple accounts to one site, as example.

**Comment by denilsonsa** [comment]
[Authenticator Pro](https://github.com/jamie-mh/AuthenticatorPro) ([GPL-3](https://github.com/jamie-mh/AuthenticatorPro/blob/master/LICENSE)) has implemented LastPass import. You can get inspired by this code (needs rewriting it from C# to Java):

* https://github.com/jamie-mh/AuthenticatorPro/blob/master/AuthenticatorPro.Core/src/Converter/LastPassBackupConverter.cs
* https://github.com/jamie-mh/AuthenticatorPro/blob/master/AuthenticatorPro.Test/src/Converter/LastPassBackupConverterTest.cs
* https://github.com/jamie-mh/AuthenticatorPro/blob/master/AuthenticatorPro.Test/data/lastpass.json

I'd suggest reopening this issue, as it is now much easier to export from LastPass than when this issue was originally closed.
