### ISSUE TITLE
Compatibility with KeePass kdbx

### ISSUE THREAD

**Issue by thomassth** [beemdevelopment/Aegis#272]
KeePass kdbx can store 2FA data as TOTP secrets in custom secret fields, and many clients across many platforms are supporting it. 

I have built my 2FA setup in KeePassium in iOS, and I hope I can bring my database back and forth to Aegis when I switch to android.

**Comment by alexbakker** [comment]
Aegis supports importing from a variety of different apps, but it only has one format it can persist to, which the Aegis [vault file format](https://github.com/beemdevelopment/Aegis/blob/master/docs/vault.md). We don't plan on changing that. So if we add support for KDBX files, you'll only be able to import them. Is that also what you had in mind?

Adding support for importing all 4 of the KDBX formats could be quite a bit of work. I've only worked with KDBX 2, which isn't too complicated, but I'm not sure about the newer versions. Are there any good Java libraries that can work with KDBX files?

**Comment by thomassth** [comment]
Keeweb does it with JS and it support kdbx v4. The java one seems to be abandoned last year so I’m not sure it’s a good idea.

https://github.com/keeweb/kdbxweb

And at the very least both import and export to kdbx needs to be implemented. No other app takes the Aegis format for now, and it would be bad if a user cannot backup their data and retrieve them in unforeseen circumstances. If I lost my phone, I hope to get a working backup useable on my iPad or computer.

Also, while not entirely in spirit of 2FA, syncing of 2FA across platforms is in high demand, with lots of proprietary solutions selling that feature to people. They deserve an FOSS solution too.

**Comment by iMartyn** [comment]
IMO export will be tricky here because 99% of the time people will want to export to their existing .kdbx file.  Keepass2Android does clever merging when things change, and you could keep an id in additional properties (kdbx already supports this nicely), but I agree, this would be fantastic as anyone who uses keepass(x/xc/...) has already had to work out how to sync the files.

Side notes:
- if looking at the keepass2android code, there's a really nice webdav->local cache implementation there
- it would also be nice to have automatic export when a new code is added
- I'd be really glad to see this implemented :-)

**Comment by michaelschattgen** [comment]
Closing this issue as we don't have plans to implement this.

**Comment by graynk** [comment]
I've had the same problem migrating from Android to iOS. So in case anyone else comes here looking for a way to export Aegis database to KeePass: I've made a simple [standalone tool](https://github.com/graynk/atk) for this. It does not merge into existing databases though, only creates a fresh one with only the TOTP codes. It also uses KDBXv4.
