### ISSUE TITLE
Don't Copy On Tap To Reveal

### ISSUE THREAD

**Issue by tERyceNzAchE** [beemdevelopment/Aegis#280]
Have option to not automatically copy when you tap to reveal a code.  Require a 2nd tap to copy.
The "code copied to clipboard" message may cover the code making the user wait several seconds before they can see the code.

**Comment by michaelschattgen** [comment]
I'm not sure if that's the correct solution since I don't think tapping the code twice is very intuitive. I was thinking of the following three options:
1. We make 'Copy on tap' a user preference
2. We make 'Don't show copy message' a user preference
3. We remove the toast completely

What do you think @alexbakker?

**Comment by alexbakker** [comment]
Let's do 1 and enable it by default. We already had a couple of users who couldn't figure out that a single tap would copy the code. I'm afraid hiding it behind two taps would only add to the confusion.

**Comment by tERyceNzAchE** [comment]
I like #1.  If it is disabled, can you have a long-press on displayed code copy to clipboard?

**Comment by shadow00** [comment]
@tERyceNzAchE but the long press is already used to select an entry - how do you replace that?
