### ISSUE TITLE
Remote export of data

### ISSUE THREAD

**Issue by RomainL972** [beemdevelopment/Aegis#292]
Hello,
I use Aegis for 2fa on all my accounts but recently my phone's screen broke and I can now only use my phone with remote access software. When I open Aegis, there only is a black screen, I suppose it's because of the "screen security" option. I managed to unlock the vault but I can't see the codes. Is there any way to export the data when the vault is open without using the app? Or is there any way to disable the "screen security" when it's on?
Thanks for your help.

**Comment by alexbakker** [comment]
Have you tried using [scrcpy](https://github.com/Genymobile/scrcpy)? It creates a secure display for its recordings, so that even protected views are shown and not blacked out.

Also, is your device rooted? Or do you have developer options enabled? If so, you could also use ``adb backup`` to create a backup of all of your apps, extract it on your PC and obtain Aegis' vault file.

**Comment by RomainL972** [comment]
Thank you so much, scrcpy worked perfectly!

**Comment by Ricky12Awesome** [comment]
This no longer works, had a very similar issue with my pixel 6

here's a screenshot of srccpy, adb backup is deprecated and doesn't work with android 12+ (and apps that target it), is there a way I can get the actual files that aegis uses and backup that? tried looking at `This PC\Pixel 6\Internal shared storage\Android\data\com.beemdevelopment.aegis\files` but it was just empty
![image](https://user-images.githubusercontent.com/29931568/228405810-ad558f86-bea0-477c-bb76-83f30e9f535c.png)
