### ISSUE TITLE
Color contrast of selected entries with amoled theme is too low

### ISSUE THREAD

**Issue by mKoonrad** [beemdevelopment/Aegis#335]
When I select few entries with enabled amoled theme color contrast of these entries is to low. On darker screen I can't see which entries ale selected. I'd like to suggest improve color of selected entries to more brighter.

**Comment by orangenbaumblatt** [comment]
Besides increasing the contrast we could change the icon to indicate whether an item is checked (like in Gmail).
![temp](https://user-images.githubusercontent.com/14238362/77051160-277cf680-69cb-11ea-81bb-313da61a0047.jpg)

**Comment by mKoonrad** [comment]
@orangenbaumblatt Good idea 👍

**Comment by orangenbaumblatt** [comment]
I had some troubles implementing the indicator icons, presumably due to the RecyclerView. If anyone wants to take a look, there is some code in my fork that basically works but is a bit laggy when scrolling.

Besides that, I've made the background color a bit lighter.
![Background color](https://user-images.githubusercontent.com/14238362/77809252-36307100-708f-11ea-95e7-65d228be4fa6.png)

**Comment by alexbakker** [comment]
@orangenbaumblatt Can you submit draft PR's for your changes? We can work on it together, if you want.

**Comment by orangenbaumblatt** [comment]
@alexbakker Sure, just wanted to know what you guys think about it.

**Comment by alexbakker** [comment]
@orangenbaumblatt We're on board with both the selection indicator icons and contrast changes.

**Comment by michaelschattgen** [comment]
Fixed in #344.
