### ISSUE TITLE
Sites don't accept my 2FA codes after restoring my Aegis backup

### ISSUE THREAD

**Issue by rodrigoswz** [beemdevelopment/Aegis#340]
###### Info

* __Version__: 1.1.4
* __Source__: Google Play
* __Vault encrypted:__ Yes (with biometric unlock)
* __Device:__ Xiaomi Mi 9T
* __Android version and ROM:__ Android 10 - March Security Patch (Pixel Experience Plus)

###### Steps to reproduce

- Install Aegis
- Restore my backup file
- Try use the 2FA codes on my accounts ¯\_(ツ)_/¯

###### What do you expect to happen?

Restore my backup file and the sites accept the code

###### What happens instead?

I restore my backup file without any problem, however the sites do not accept the code. I tried to use the Aegis codes installed on my tablet and it worked perfectly.

For testing, I tried to restore an encrypted backup and an unencrypted backup, both with the same problem. I also tried to backup my tablet data with Titanium Backup and restore it on my phone, to my surprise the problem persisted.

I've been using Aegis since it was announced and I've never had this kind of problem, I don't know what to do to find out what it is.

I am willing to help in whatever is necessary, this is a huge problem for me. Luckily I have my tablet with the same saved entries.

**Comment by alexbakker** [comment]
Is the system time on your device correct? Is your device configured to sync the time automatically?

**Comment by fabianski7** [comment]
I was having the same problem and it really was the watch that wasn't synchronized.

Since you're using a custom rom, it may not have configured an ntp server by default. Use some app like [NTPSync](https://f-droid.org/pt_BR/packages/org.ntpsync/) (maybe it doesn't work on android 10) or [NTP & GPS Clock](https://play.google.com/store/apps/details?id=jp.xrea.poca.clocksync) ([no ads or trackers](https://reports.exodus-privacy.eu.org/en/reports/jp.xrea.poca.clocksync/latest/)).

Or do it manually: https://gist.github.com/xujiaao/63cb3bbea9fe22e79206e5eb7ba82d0e

**Comment by rodrigoswz** [comment]
A few hours later, without doing anything, I tried again and my codes just worked. The system time was correct.

I can't say what happened, I think I can close this issue. Thank you all for the attention!
