### ISSUE TITLE
In the sort order menu, we see "custom". But then there's no way to customize that.

### ISSUE THREAD

**Issue by jidanni** [beemdevelopment/Aegis#357]
In the sort order menu, we see **custom**. But then there's no way to customize that.

**Comment by michaelschattgen** [comment]
There is. Hold the entry until it's selected, then drag and drop it to your preferred position.

**Comment by jidanni** [comment]
Well that I would label as "Current".
A "Custom" label would need a corresponding Setting where the user could customize it.

**Comment by michaelschattgen** [comment]
It stands for 'Custom sort', which it is. You customize the sort by dragging the entries.

**Comment by maximbaz** [comment]
It took me a while to figure out why drag-n-drop didn't work for me - turns out, probably intentionally, this isn't supported when you are filtered down to a single group - although this is probably more related to #126 which could replace filters altogether.

There is a tiny bug by the way:

- Select a single group in filter
- Hold an entry until its selected
- Try to drag-n-drop it (will not work)
- Tap on another entry (so that two entries are selected)
- Tap on that another entry to unselect it
- Drag-n-drop the first entry again - now it will be dragging, but it won't actually remember the new position

**Comment by michaelschattgen** [comment]
Nice find, I've created a new issue for this.
