### ISSUE TITLE
Support for RSA SecurID Tokens

### ISSUE THREAD

**Issue by 45054** [beemdevelopment/Aegis#372]
It would be wonderful, if support for SecurID-Tokens could be implemented in Aegis.

There are Open Source implementations but unfortunately development has stalled:

https://github.com/cernekee/EasyToken
https://github.com/cernekee/stoken

**Comment by alexbakker** [comment]
Are RSA SecurID tokens still common? I've only had to use it once for PuleSecure. I'd personally rather watch SecurID fade into obscurity than spend time on implementing support, but perhaps someone else is willing to do so and contribute a patch.

Has development of those open source projects stopped because they are done, or are they unfinished? And if they're unfinished, why? Does RSA change the SecureID algorithm so often that the projects need continuous development?

**Comment by 45054** [comment]
Unfortunately in the corporate field SecurID is still rather common. And I wholeheartedly share your wish for it to fade into obscurity.

As for stoken for example there is a pull request for decoding support for a newer version of RSA tokens that did not get merged as of now: https://github.com/cernekee/stoken/pull/51 - so yes there appears to be ongoing development in regards to this token technology.

The existing app may work fine for its use case but it doesn't support multiple tokens for example: https://github.com/cernekee/EasyToken/issues/1

Also it would just be convenient to have various tokens accessible in one app that is still developed actively.

**Comment by michaelschattgen** [comment]
Closing this issue as we don't have plans to implement this. If someone wants to take responsibility of implementing this, feel free to restart this discussion.
