### ISSUE TITLE
[Bug] Problem with biometrics

### ISSUE THREAD

**Issue by wododoporny** [beemdevelopment/Aegis#384]
App will crash immediately after tapping Biometric and holding my finger on sensor. Is an issue because I don't remember my password.

**Comment by alexbakker** [comment]
Please fill out the bug report template. Please also record a log of the crash with ADB and share it here (https://github.com/beemdevelopment/Aegis/blob/master/CONTRIBUTING.md#capturing-a-log-with-adb).

My guess would be that this crash happens because changes were made to the security settings of the device. See #94. Is that the case? Aegis should have shown a message saying "A change in your device's security settings has been detected", but some devices have a poor Keymaster implementation and don't properly report that.

**Comment by alexbakker** [comment]
I'm going to close this, as we haven't received a follow-up. Feel free to reopen if this is still an issue for you, @wododoporny.
