### ISSUE TITLE
Ask directly for fingerprint if biometrics configured

### ISSUE THREAD

**Issue by techexo** [beemdevelopment/Aegis#399]
Hello,

I am using Aegis 1.1.4 installed from fdroid and I'm always troubled when I launch the app.
Indeed, even if I have biometrics authentication/unlock configured, I need two clicks + my fingerprint to access my codes! (click on the password field, select biometrics, then use fingerprint)

It would be great to have an option allowing one to automatically ask for the fingerprint when launching the app, so that we have a quick access to codes. 

I have a fingerprint reader under the screen, not directly accessible without prompting the biometrics reader, I don't know if that changes anything for my request.

Best regards
Eloi

**Comment by michaelschattgen** [comment]
Hi Eloi, thanks for your report. It seems like this is a bug since the prompt should automatically pop up. It could be a limitation from OnePlus to prevent accidental authorizations if an app could just show the prompt without user interaction.

Do you have other apps that do work properly, do these apps trigger the prompt automatically?

**Comment by alexbakker** [comment]
Please also fill out the bug report template.

**Comment by acolombo25** [comment]
> Hi Eloi, thanks for your report. It seems like this is a bug since the prompt should automatically pop up. It could be a limitation from OnePlus to prevent accidental authorizations if an app could just show the prompt without user interaction.
> 
> Do you have other apps that do work properly, do these apps trigger the prompt automatically?

At the moment the same thing is happening on my Samsung S10E (physical fingerprint sensor, not on-screen), so I don't think it's limited to OnePlus.
When opening the app it's asking me to enter my password, so I have to press back and then I have to press the biometrics button for the fingerprint authorization to be prompted. If the prompt should be automatic and that's how it works on other devices, then I will try debugging it tonight on my device.

**Comment by alexbakker** [comment]
@michaelschattgen suggested that this may be due to the fact that Aegis reminds you to enter your password every once in a while, as shown here: https://github.com/beemdevelopment/Aegis/pull/293. However, sometimes auto-fill popups may be rendered over that, as shown here: https://github.com/beemdevelopment/Aegis/issues/383. Could that be the case here?

**Comment by acolombo25** [comment]
> 
> 
> @michaelschattgen suggested that this may be due to the fact that Aegis reminds you to enter your password every once in a while, as shown here: #293. However, sometimes auto-fill popups may be rendered over that, as shown here: #383. Could that be the case here?

No you're right, the text below the field reminding me to enter my password is what's happening.

The confusing part is that you're not forced to input the password, but can still use the fingerprint anyways. I've read the text many times but glanced over it since there still is the button to use the fingerprint.

But yeah there's no bug then, it's actually fine how it works, it's just a bit uncommon of a behavior compared to other apps.

**Comment by alexbakker** [comment]
> The confusing part is that you're not forced to input the password, but can still use the fingerprint anyways. I've read the text many times but glanced over it since there still is the button to use the fingerprint.

This is by design. If you forget your password, you would want to be able to unlock with biometrics and change it.

Well think of a better place to place the reminder popup though, so that auto-fill popups aren't rendered on top of it.

**Comment by michaelschattgen** [comment]
If you have any suggestions about how we can improve this while keeping it prominent feel free to comment.

**Comment by techexo** [comment]
You were absolutely right, I didn't see the "it's been a while" comment! It works as intended once I unlocked it with password once again. Sorry for the disturbance!

**Comment by michaelschattgen** [comment]
No worries! We should definitely do something with this.
