### ISSUE TITLE
Change color of code before it expires.

### ISSUE THREAD

**Issue by DaVoodoo** [beemdevelopment/Aegis#411]
I propose that the color of the code changes to red just before it expires. (Perhaps 7 seconds?)

Steam Guard has this and I think it will look really good in Aegis.

Normal:
<a href="https://imgur.com/ZWgasOl"><img src="https://i.imgur.com/ZWgasOlm.jpg" title="source: imgur.com" /></a>

Less than 7 seconds left:
<a href="https://imgur.com/zi3bYM7"><img src="https://i.imgur.com/zi3bYM7m.jpg" title="source: imgur.com" /></a>

**Comment by Wilker-a** [comment]
more visual cues means less time looking for the bar at the top \^\^

**Comment by claytondaley** [comment]
I agree that the single, slowly moving bar at the top is inadequate.  However, I don't feel like something discrete like changing colors is ideal behavior for me.  If I'm tying a TOTP in my computer, 2 seconds may be more than enough to get those six digits submitted.  If I have to switch apps on my cell phone and find a TOTP field that has lost focus, I could miss longer windows.

My "minimum effort" change would probably be to repeat the countdown progress bar between each set of codes.  I've seen other things that I like (like a bar that circles around each icon), but the usability is more important than the specific visual.

**Comment by IiroP** [comment]
Yeah, I liked that feature in LastPass Authenticator (codes were red for the last 5 seconds I think). Of course it could be optional feature, maybe even with option to change the duration.

**Comment by anthonymaers** [comment]
Completely agree, this is a must have!

**Comment by morbac** [comment]
I also agree: this feature would be very useful.
The top bar is not visible enough and it is very frustrating to see the 6 digit code change in the middle of an input.

**Comment by davebeep** [comment]
Just moved from andOTP, which did this and I found it really useful. (Also used Lastpass authenticator in the past and think that did it too). Would be great - please try to implement! Cheers

**Comment by gordonjb** [comment]
LastPass Authenticator (which I'm in the process of moving from) recently added a really neat feature when as well as indicating when the code is about to rotate, it now also shows you what the next code will be so you can just start entering that one instead rather than rushing to complete the old one

**Comment by daveTheOldCoder** [comment]
I was going to request a feature to add a timer that show much time is left before the codes refresh. While looking to see if the request had already been made, I found this issue and learned that the feature is already present. :)

I think that shows that the bar at the top needs to be more visible, or at least mentioned in the documentation.

**Comment by markus-ksg** [comment]
See also #923. It would be better to show something useful (previous or next code) instead of just changing the color.

**Comment by claytondaley** [comment]
These aren't mutually exclusive:

- If you show the next code, it's not valid immediately so you need a visual indicator. No one wants to submit a code 5-10 seconds early and have it fail.
- Showing the previous code is less problematic because most sites have a ~30 second grace period while both work.  You could finish a code started right before the window shifts (without the need for colorization).
- I don't think most people know this (or that it's guaranteed by the standard) so a lot of users will be confused by the extra codes and prefer a simple color indicator so they know whether or not to start the current code.

**Comment by mdr92** [comment]
I'd like to see this added too, it's the reason I went back to AndOTP, it turns red (the codes and the bar) for the last 10 seconds and if I see that I wait for the next code. Otherwise it's too easy to start typing a soon to expire code (I know about the grace period, but it's often gone before you've finished typing it), a clear visual indicator would be much better. Thanks
