### ISSUE TITLE
Support importing encrypted andOTP backups

### ISSUE THREAD

**Issue by badgooner** [beemdevelopment/Aegis#46]
Screenshot: https://i.imgur.com/wCYO7OS.jpg

**Comment by alexbakker** [comment]
Encrypted andOTP backups are not supported. Could you try a plain text one?

**Comment by alexbakker** [comment]
We'll repurpose this issue to track adding support for importing encrypted andOTP backups.

**Comment by Ahmd1440** [comment]
🔴ATHEISM EXPLAINED IN 45 SECONDS

https://youtu.be/uwqPdWZvjAY

⚠️🔴⚠️🔵⚠️

🔵THE MEANING OF LIFE "SPOKEN WORD"

https://www.youtube.com/watch?v=7d16CpWp-ok

⚠️🔴⚠️🔵⚠️

🔴 If we would like to know if a religion is true or false, we should not depend on our emotions, feelings, or traditions. 

🔵 Rather, we should depend on our reason and intellect...👇

📚 Some Evidence for the Truth of Islam 📖

https://goo.gl/7QVdzz

⚠️🔴⚠️🔵⚠️

🔴 Islam is not just another religion. 

🔵 It is the same message preached by Moses, Jesus and Abraham.

🔴 Islam literally means ‘submission to God’ and it teaches us to have a direct relationship with God. 

 🔵 It reminds us that since God created us, no one should be worshipped except God alone. 

🔴 Becoming a Muslim is not turning your back to Jesus. 

🔵 Rather it’s going back to the original teachings of Jesus and obeying him. 


More .....👇

🔴 THE RETURN OF JESUS


https://jesusen1.blogspot.com/2017/12/what-is-islam.html
