### ISSUE TITLE
Rootless import from Google Authenticator

### ISSUE THREAD

**Issue by infokiller** [beemdevelopment/Aegis#466]
Google [recently added export](https://security.googleblog.com/2020/05/introducing-portability-of-google.html) to Google Authenticator, though it only supports importing from Google Authenticator in another device.
However, [this blog post](https://www.ctrl.blog/entry/google-authenticator-2fa-secrets.html) suggests it may be a just an encoded protobuf.
It would be really great if Aegis supported importing from this, and I think it could really increase adoption because most users don't want to root their phones (and rooting also compromises the security of the phone).

**Comment by michaelschattgen** [comment]
Thanks for your feature request. We already implemented this in #406! 

This feature is currently available in the beta channel in Google Play Store. We plan to release this to production within a few days.

**Comment by infokiller** [comment]
Sorry I missed that, you guys rock!
Eagerly waiting for it to land in prod!

**Comment by maxailloud** [comment]
@michaelschattgen I see that it is suppose to have landed in the Android app in the 1.2 version but I don't find the option.
Surely my blindness (it's ironic I am not blind) working against me. Is there a way to import the Google Authenticator QR code in Aegis?
By the way awesome app that I just discovered and gonna use instead of Google Authenticator, even if being able to import my codes form it would be even better.

**Comment by maxailloud** [comment]
Ok my bad for being stupid, I just didn't think of scanning the QR code like a regular QR code.
Anyway keep up the good job 👍

**Comment by michaelschattgen** [comment]
Haha no worries! I'm glad it worked for you.
