### ISSUE TITLE
[UX] Biometric unlock requires several screen touches before fingerprint accepted

### ISSUE THREAD

**Issue by khimaros** [beemdevelopment/Aegis#522]
First of all, this is an amazing product and I'm extremely grateful for this open source tool!

I use biometric unlock as the only authentication mechanism for Aegis.

Each time I want to unlock, I'm prompted with the password screen and need to take several steps before I can authenticate:

1) close the keyboard, sometimes requires multiple touches
2) press the (very small) "biometrics" touch target
3) finally authenticate with my fingerprint

Is there any way to enable the biometric entry without requiring any screen touches?

**Comment by alexbakker** [comment]
Aegis will periodically ask you to enter your password, so that you don't forget it. When it does so, it displays a popup below the password field, is that not visible on your device? After you've entered your password once to dismiss the reminder, Aegis will start automatically asking for biometrics again, until it's time for another reminder. You can also disable the reminder entirely in the settings.

**Comment by khimaros** [comment]
Aha, that did it, thank you @alexbakker! That said, it wasn't clear that the password prompt was being presented for that reason, so maybe still some opportunity for UX improvement in that regard.

**Comment by alexbakker** [comment]
Did Aegis not show a popup? As shown in this screenshot: https://alexbakker.me/u/6wjf81g184.png.

**Comment by khimaros** [comment]
I see now; the Aegis pop-up was being obscured by a "Autofill with Bitwarden" pop-op.

I think this can be closed. Apologies for the noise!
