### ISSUE TITLE
Biometric lock disabled, settings inaccessible so can't re-enable, no password set/remembered

### ISSUE THREAD

**Issue by YenRug** [beemdevelopment/Aegis#576]
###### Info

* __Version__: 1.3
* __Source__: Google Play
* __Vault encrypted:__ Yes (with biometric unlock)
* __Device:__ Samsung Galaxy Note 9
* __Android version and ROM:__  10 ROM?

###### Steps to reproduce

Opened Aegis Authenticator

###### What do you expect to happen?

For it to use my biometrics to unlock

###### What happens instead?

It's asking for a password, don't recall setting one and likely variants I would normally use aren't working. There's an info message stating:

A change in your device's security settings has been detected. Please go to "Aegis -> Settings -> Biometrics" and re-enable biometric unlock.

Kind of hard to change the settings when I can't get into the app in the first place!

###### Log

```
If applicable, paste the debug log here.
```

**Comment by michaelschattgen** [comment]
I'm sorry but there is nothing we can do here. You've set a password in the intro the first time you've started Aegis. 

When you make changes to the security settings of your device, the Android Keystore key is invalidated by Android and can no longer be used by Aegis. Therefore you can't unlock your vault with your fingerprint.

You would have to contact the service(s) where you have the account to see if they can help you out.

**Comment by Dazul** [comment]
I am commenting here because I got the exact same issue. I do not remember Aegis asking me for a password while installing it (yesterday). And as I was still finishing to configure my phone, I did not made any backup yet.

And now I am locked out because I do not have any password set, and Aegis will not let me use biometrics.

**Comment by alexbakker** [comment]
Aegis always asks for a password during setup, so you must have entered one.

What makes you say that Aegis will not let you use biometrics? Is it showing you an error message? Or is it telling you that a change in the security settings of your device was detected?

**Comment by salman2learn** [comment]
Experienced the same message and had forgotten the password. I had backup to restore.
For UX perspective, it would help to periodically show a reminder to remember the password, or ask for password instead of or besides biometrics (happens on android).
Its easy to forget that there was a password when using biometrics have been in use for long time.

**Comment by michaelschattgen** [comment]
@salman2learn Aegis already shows a password reminder whenever it's been a while since you've entered yours. It stops the biometrics popup from showing and asks you to enter your password. This setting is enabled by default and can be found under Security -> Password reminder. You probably turned this off at some point.
