### ISSUE TITLE
What password is used with backups?

### ISSUE THREAD

**Issue by edent** [beemdevelopment/Aegis#580]
I'm confused about how backups work. I unlock the app using biometrics. When I backup the database, I don't get prompted to enter a password.  I want to store the backup in the cloud and restore it if I get a new phone. But without knowing the password, I don't see how I can do this.

On andOTP, I exported the database, set a password, then used that password when importing to Aegis.

So what password does Aegis use for backups?

I think this is related to #121

**Comment by alexbakker** [comment]
Aegis uses the same password for backups as the one you set during initial setup of Aegis. If you've forgotten it, you can change it in the settings.

**Comment by ThiefMaster** [comment]
Would it be possible to use a separate password or GPG? Considering that my phone has a lockscreen and is usually with me all the time, I use a "somewhat easy to enter" password (even though biometrics make entering it very rare). However, for cloud backups I'd rather have something stronger (or GPG).

In fact, GPG support is one of the features in andOTP which I like a lot: I just export the backup and on the PC it's easy to decrypt, but on the phone (or cloud storage) it's impossible to decrypt it (since the private key isn't on there).
