### ISSUE TITLE
Backup database compression

### ISSUE THREAD

**Issue by DerRockWolf** [beemdevelopment/Aegis#599]
Hi, would it be possible to add database compression to minimize the size of the backups?
They are quite huge (1.2MB with 16 entries) compared to a kdbx file with 90 entries (60kB)...

**Comment by alexbakker** [comment]
Do you have icons for your entries in Aegis? That's probably what makes up most of the size of your vault file. If you'd like, you can try experimenting with compressing the ``db`` section of the vault file, but I don't think those icons will compress very well.

**Comment by DerRockWolf** [comment]
Yes, I'm using logos...

But what's weird about it, is that I'm using 9 logos that are together around 84,78kB in size, but the db file is 1.2MB in size...

Something doesn't seem to fit here.

**Comment by alexbakker** [comment]
You're right, the way icons are stored is currently very inefficient. Currently, Android renders the image first (so that the user can crop the image if they want) and we then extract that to store it as a JPG. This will be addressed indirectly by #539, by using the source image file directly. There will still be some overhead due to the base 64 encoding, but nothing close to what you're seeing now.

I don't think we need to add support for compression though, so I'll close this.
