### ISSUE TITLE
Can't extend OTP Lifetime (to 1 min.) and/or Hash Algorithm (to SHA256) while Google Authenticator does

### ISSUE THREAD

**Issue by Sloepie** [beemdevelopment/Aegis#635]
Sorry, I am not a programmer. I just like to notify you about this problem, as the same settings work fine with Google Authenticator, but not with Aegis

I am using TOTP from FreeRadius. When I use the default TOTP settings both Aegis and Google Authenticator work as they should. Though the default FreeRadius settings are 20 seconds and MD5.  Aegis seems to be set however to a OTP Lifetime of 30 seconds and the Hash Algorithm to SHA1

However when I want to extend the OTP Lifetime in Aegis from the default 30 seconds to 60 seconds, Google Authenticator changes the lifetime accordingly, while Aegis keeps working at the 30 seconds interval. It does not matter whether I use the QR code and/or set the desired values manually. 

I get the impression Aegis (internally) resets every time to its default settings of 30 seconds and SHA1

The file enclosed shows my Freeradius settings with which Google Authenticator works automatically and Aegis not at all.
![totp-config-settings](https://user-images.githubusercontent.com/11617042/102697095-4eef4100-4233-11eb-96a7-b0c84c2d5da6.jpg)

###### Info

* __Version__: 1.3
* __Source__: (Google Play/GitHub/F-Droid/?) F-Droid
* __Vault encrypted:__ Yes (with biometric unlock)/Yes/No Yes
* __Device:__ Redmi5 Plus
* __Android version and ROM:__Android 10 Lineage_
Vince
###### Steps to reproduce

A detailed list of reproduction steps.

###### What do you expect to happen?

...

###### What happens instead?

...

###### Log

```
If applicable, paste the debug log here.
```

**Comment by alexbakker** [comment]
Google Authenticator only supports tokens with a period of 30 seconds and SHA1 as the hash algorithm. When you present it with a QR code that sets SHA256 and a non-standard period configuration for example, it will ignore that and use the defaults instead.

The screenshot of the settings page you shared seem to be for mOTP. Aegis doesn't support this (and neither does Google Authenticator). Where are the settings for TOTP?

I'm getting the feeling that you're editing a set of options for mOTP,  but are actually using TOTP to log in.

**Comment by Sloepie** [comment]
Hello Alex,

It is not clear to whether you mean that Aegis only supports a period of 30 seconds, or also Google Authenticator supports only 30 seconds? 

If you really meant Google Authenticator, then you are dead wrong. The code stays absolutely valid for one minute on Google Authenticator and only changes every minute, not every 30 seconds! And I am using it on my own servers, entering the codes frequently in the last few seconds, just before the next minute.

Also your "feeling" about mOTP is wrong. I use TOTP 100% Not only with Google Authenticator, but also with Aegis, albeit only every 30 seconds. How else could I also login to my system with Aegis if, as you claim yourself, Aegis (and Google) don't support mOTP. Beside that; how could it ever be mOTP if it also works when I put the phone in flight mode? Furtemore I have never seen a mOTP authenticator that also changes the code after 30 or 60 seconds

Concerning the hash vaulue: Googel Authenticator accepts the SHA256 setting, but ofcourse I can't rule out that also Google sets it back to SHA1 internally. I did not test that yet.

So as Google allows a period of at least 1 minute (maybe even more, bit I did not test that yet), why does Aegis only allow 30 seconds? I thought even 2 minutes is still acceptable for security.

**Comment by alexbakker** [comment]
> It is not clear to whether you mean that Aegis only supports a period of 30 seconds, or also Google Authenticator supports only 30 seconds?

That was just about Google Authenticator. Aegis *does* support different periods, hash algorithms and digit counts. I would be very interested in a demonstration of Google Authenticator supporting periods other than 30 seconds. Note that the fact that the server may accept the code after the 30 seconds have elapsed is something entirely different.

> Also your "feeling" about mOTP is wrong. I use TOTP 100%

The reason for that feeling is because your screenshot literally says Mobile-One-Time-Password (mOTP) and makes no mention of TOTP. It also says that the code is calculated with ``EPOCHTIME+INIT-SECRET+PIN``. TOTP does not have the notion of a ``PIN``, but mOTP does. So, my thought process is: you're making changes to the mOTP settings, but actually have TOTP configured someplace else and are using that to log in. I'm not familiar with FreeRadius though, so I'll leave that up to you to check.

> Beside that; how could it ever be mOTP if it also works when I put the phone in flight mode?

mOTP functions without an internet connection, so I'm not sure what you think putting your phone in flight mode will accomplish.

> So as Google allows a period of at least 1 minute (maybe even more, bit I did not test that yet), why does Aegis only allow 30 seconds? I thought even 2 minutes is still acceptable for security.

Aegis does support different period settings. Could you take a screen recording of what you're seeing in Aegis? Start with the edit entry screen, showing the settings you have there, and then go back to the main screen and demonstrate that Aegis ignored that period setting.

**Comment by alexbakker** [comment]
No response. Closing.
