### ISSUE TITLE
Import from Authenticator Plus: Error "Error trying decrypting database"

### ISSUE THREAD

**Issue by dnkrupinski** [beemdevelopment/Aegis#665]
Details: java.io.FileNotFoundException: Accounts.txt

But this file is included in the ZIP-file.

**Comment by dnkrupinski** [comment]
Find solution in 

`Unable to import from Authenticator Plus #607 `:

Take the ZIP file, remove html file so there is only the Accounts.txt left. 
The import will work!

**Comment by alexbakker** [comment]
This will be fixed by #664.

**Comment by elieobeid7** [comment]
I had this error, I exported them as plain text from authenticator plus, it's an option inside the app then reimported them, worked fine.  

No need to worry about security, just delete the text file once the import is done, authenticator plus is dead.

**Comment by dnkrupinski** [comment]
As far as i know, there is no option to export the entries from Authenticator Plus to a single text file; you can only export the informationen to a db file. But if you delete the html file inside the zip file (the Accounts.txt will remain), the import in Aegis will work as expected.

**Comment by elieobeid7** [comment]
Oh you're right, I exported it as HTML then re-imported it, and it worked fine

**Comment by lozzd** [comment]
How did you modify the zip file to remove the HTML file? Android, Windows and macOS cannot open it or modify it. macOS at least asks for the password but the password I entered doesn't work - other tools see it as compressed with a format the don't understand. 
(Meanwhile Aegis won't open it due to the file not found error, but if you enter the wrong password it correctly says the passwrod is wrong, so I think the zip file is fine)

**Comment by dnkrupinski** [comment]
I can open the ZIP file with PowerArchiver and also with Total Commander with the chosen password.

**Comment by lozzd** [comment]
@dnkrupinski Total Commander worked perfectly! Thank you!

**Comment by dnkrupinski** [comment]
You are welcome! Total Commander is **The** Switzerland Army Knife.
