### ISSUE TITLE
Chrome Browser Extension

### ISSUE THREAD

**Issue by archit9169** [beemdevelopment/Aegis#674]
TOTP Authenticator has this feature called chrome extension. I don't know how exactly that works but i think they might be using some google services to pass the pin as string from android app to chrome extension. It requires signing in with google id for this feature to work on both the extension and the app.

Is it possible to implement this in the future? I dont think a seperate server is required for this unlike the case with push notification feautre like lastpass or microsoft authenticator. Since i think google services can be used for this?

Please share your thoughts.

Edit :- Another app with similer feature 2FAst. Although they use their own proprietory service so yeah there is that.
Links :- 
            1. 2FAst android app :- https://play.google.com/store/apps/details?id=com.pinapps.codesender
            2. 2FAst chrome ext :- https://chrome.google.com/webstore/detail/2fast-code-sender/djjophdaemcafajdpmbhfneamdmhhnkl?hl=en

**Comment by alexbakker** [comment]
Thanks for your suggestion, but Aegis is an offline-only app and we don't have plans to change that. Using Google's services is also a non-starter.

**Comment by Marko-98** [comment]
Hey @alexbakker ! 👋

I can see that you said that this wasn't planned. May I ask if your position on browser extension changed? 

If you think about it, browser extension makes a lot of sense. Not only it would save people time (and even if they lose a phone still have access to their accounts), but you killed multiple birds with one stone. (I know backup option exists, but this could be lifesaving for those that don't have it enabled.)

And you just need to develop one extension, then port it for two different browser-engines, Mozilla's Gecko and Google's Chromium. By developing browser extensions, you made your product universally available for Windows/Linux/macOS, as well as, multiple web browser considering all of them are just forks. Without the need to create separate apps.

Looking forward to your answer. Thanks for developing this wonderful app, which is by far the best 2FA app that exists, even though I miss browser extension so much.

Best regards,
Marko

**Comment by michaelschattgen** [comment]
Hi Marko, our stance on this has not been changed. While we understand the benefits of having a browser extension, we'd rather keep Aegis an offline-only app. Personally I am also a firm believer of retrieving 2FA codes on the device you're trying to login with kind of defeats the purpose of actual 2FA.

**Comment by Marko-98** [comment]
Hi @michaelschattgen ! Thanks for fast reply!  🙂

> While we understand the benefits of having a browser extension, we'd rather keep Aegis an offline-only app.

I totally support having Aegis offline-only, and when I asked about browser extension, I had that in mind. My implementation idea was for extension to have import option for backup created by the app, without the need for a server or 3rd party service. 

> Personally I am also a firm believer of retrieving 2FA codes on the device you're trying to login with kind of defeats the purpose of actual 2FA.

May I know why? I always looked at 2FA as just additional security measure needed for signing in. I'm not sure this would defeat the purpose of 2FA because if someone guesses your password, they still need to know 2FA code which they don't have. Currently, it's just an inconvenience, because you always need to have your phone with you to sign-in.

Unfortunately, I'll have to look for alternative or at least some solution to I keep Aegis on my device, while have another app on WearOS and my PC. 

Thanks again!
