### ISSUE TITLE
App doesn't react to QR codes surrounded by dark background

### ISSUE THREAD

**Issue by mmatous** [beemdevelopment/Aegis#677]
###### Info

* __Version__: 1.4.1
* __Source__: F-Droid
* __Vault encrypted:__ Yes
* __Device:__ Motorola Moto Z Play (addison)
* __Android version and ROM:__ 8.0.0, stock

###### Steps to reproduce

Try to scan QR code surrounded by dark background, e.g. a site with dark mode on.

###### What do you expect to happen?

QR code gets scanned.

###### What happens instead?

The app doesn't recognize the QR code.

---
Alternatively, if the scanner can't be persuaded to work with such QR codes (andOTP couldn't detect it either), can the app at least detect trying to scan something like that and offer feedback that users should try switching the site theme? Or display that outright upon activating the QR scan.

It took me quite some time of waving the phone around and trying another app before realizing what might be the problem.

**Comment by alexbakker** [comment]
Which service showed you a QR code that you couldn't scan with Aegis? Could you retry with the APK linked in this comment: https://github.com/beemdevelopment/Aegis/issues/657#issuecomment-763076785?

**Comment by mmatous** [comment]
Tried the build and there's no change. The web in question is https://invictuscapital.com/.

**Comment by alexbakker** [comment]
I created a throwaway account. When turning on dark mode on this site, I think the QR code becomes invalid, because the finder pattern portion has almost the same color as the background.

We don't really get any feedback from ZXing other than 'no qr code found' and 'qr code found', so there's not much we can do here. Invictus Capital needs to fix how they display the QR code in dark mode.
