### ISSUE TITLE
When Tap to reveal is enabled change how tap to copy works

### ISSUE THREAD

**Issue by JacopoMolteni** [beemdevelopment/Aegis#690]
When Tap to reveal and tap to copy are both enabled use a second tap to copy or show a copy button near the item.
Like in andOTP it would be nice to have a way of displaying an hidden code without automatically copying it but also have a way to quickly copy an item without having to select it with a long press.
In andOTP there's a copy button that is always near the code, hidden or not, so to copy it you dont have to show it and when you show it you don't have to copy it.

**Comment by Hacker437** [comment]
@alexbakker Can I make a pull request by adding a copy button beside the code

**Comment by alexbakker** [comment]
@Hacker437 We think a copy button on the entries themselves wouldn't really fit well in Aegis' UI. So we're only going to implement the main part of this proposal. That is, we're going to change the behavior of "tap to copy" when "tap to reveal" is also enabled. If you'd like to implement that, feel free to submit a patch!

**Comment by Hacker437** [comment]
@alexbakker Thanks for replying for every comment I make and comming the issue if possible I will make it

**Comment by alexbakker** [comment]
@Hacker437 That's exactly right.

**Comment by ThiefMaster** [comment]
I'd love to see this as well. There are only few OTP codes I need on the phone (so for those I'd tap again to copy), but without tap-to-copy it's really cumbersome to copy right now (for the few codes, including one for my work account, that I do use frequently on my phone).

**Comment by alexbakker** [comment]
Implemented by #1016.

**Comment by tjkirch** [comment]
Would it be possible to have an option to disable this, or to do the reverse?  Usually I need to copy a code, and there's no need to reveal it, so this just doubles the required interactions for me.

**Comment by alexbakker** [comment]
I don't mean to come off as dismissive. I was genuinely interested in the use case. 

For us, this issue was more about fixing the odd situation where you could configure Aegis to perform 2 actions (revealing and copying a code) on a single tap. It doesn't make much sense to also copy the token every time you tap to reveal it. Since with typical usage of 2FA apps, the need to reveal a token occurs more often than the need to copy a token, we changed it so that copying requires a second tap.

I don't think it's worth the trouble to add an option for the reverse, unless there's a compelling reason to do so. If you need to copy a token without revealing it, you can long press an entry and tap the copy button that appears at the top.

**Comment by ssssamstrup** [comment]
I'd also like for the feature to return. I don't understand how adding an extra tap can be better ui. If you don't want to copy the code when revealing it you can turn that option off. 

I thought the app had been broken for a while and didn't know I suddenly needed to tap an extra time.

It doesn't seem very rational that the code isn't copied, when tap to copy is turned on.
