### ISSUE TITLE
Lock the database after x minutes of inactivity

### ISSUE THREAD

**Issue by alexbakker** [beemdevelopment/Aegis#7]

**Comment by alexbakker** [comment]
I've been thinking about this for a bit, but there doesn't seem to be an easy way to do this. Obviously we could simply lock the application after a period of time, but that'd be annoying if you're still interacting with the app. Activities can override [onUserInteraction](https://developer.android.com/reference/android/app/Activity#onUserInteraction()), but there are lots of edge cases where it's not called, like when a dialog is shown.

The least we can do for now is automatically lock when the back button is pressed in MainActivity or when the device itself is locked.

**Comment by chiraag-nataraj** [comment]
Maybe you can look into the way [Signal](https://github.com/signalapp/Signal-Android) does this, since they have an inactivity timer for locking.

**Comment by shaicoleman** [comment]
An alternative way which might be simpler to implement is a setting:
"require authentication every n minutes"
Then you only need to check when was the last time it was unlocked

**Comment by alexbakker** [comment]
I wonder if there is still interest in this feature now that we have an auto lock on minimize option.

**Comment by shaicoleman** [comment]
@alexbakker , for me the other options would require unlocking it too frequently. When I need to use the app, I often require multiple different codes over a short period. During that time, my phone would be locked and I would be switching apps frequently. At the moment I have to disable the automatic locking feature, because it gets triggered too often for me.

An option of either "require authentication every n minutes", or "require authentication after n minutes after last use" would do the trick.

**Comment by alexbakker** [comment]
We currently don't have plans to implement this, so we'll close this. We think that the options that currently exists for auto locking are sufficient for most users.
