### ISSUE TITLE
Import from Google Drive imports only 12 out of 33 items

### ISSUE THREAD

**Issue by hjo1620** [beemdevelopment/Aegis#730]
Sry for badly formatted bug.

I exported 33 items encrypted in Aegis format to Google Drive, from ASUS phone.
I imported same file from Google Drive using Samsung pad.
I selected to override, and replace whole database.
Only ca. 12 items out of expected 33 were imported.

I then exported 33 items un-encrypted in Aegis format to Google Drive, from ASUS phone.
I imported unencrypted file from Google Drive to Samsung pad.
I selected to override, and replace whole database.
All 33 items out of expected 33 were imported.

Since export "seems" to work fine, 
I assume the import of the encrypted file is silently failing.

I tried export/import of encrypted file twice, with same issue.
I tried export/import of un-encrypted file once, without issue.

**Comment by alexbakker** [comment]
> Sry for badly formatted bug.

Apologies not accepted, please fill out the bug report template ;)

Is this reproducible? I.e. can you try to create a new encrypted backup and import it? Are there still entries missing?

How sure are you that the encrypted file you're trying to import is not an old backup of your vault? I'm asking because if the vault was corrupted somehow during backup, Aegis would report that, and not import just half of the entries.

**Comment by hjo1620** [comment]
Cannot reproduce today.
You can close this.
