### ISSUE TITLE
Tap to copy / reveal

### ISSUE THREAD

**Issue by erdnuesse** [beemdevelopment/Aegis#742]
I like the tap to reveal and copy option. 
context:
Sometimes though, I don't even need the reveal option, so it would be great:
I can have all codes hidden, and tap to copy without revealing.
example: - > tap to copy - long press for revealing

Idk the best way how to implement it, but I can imagine there being many security-aware ppl. who like to copy without showing anything on-screen. 

best regards

**Comment by alexbakker** [comment]
Thanks for the suggestion. In the rare cases where you need to copy a token without revealing it, you can long press on an entry and press the copy button at the top action bar. So I don't think it's worth adding a separate option for this. Especially since we already have a bunch of options that influence the behavior and look of the entry list and adding even more will make it difficult to maintain.
