### ISSUE TITLE
List beta builds on F-Droid

### ISSUE THREAD

**Issue by alerque** [beemdevelopment/Aegis#746]
Being an F-Droid user myself and affected by one of the bugs you list as fixed in the 2.x beta release notes, I would be interested in trying beta builds.

I did a quick search in the F-Droid forums and found (ironically) [this tidbit regarding andOTP betas](https://forum.f-droid.org/t/provide-beta-versions-of-andotp/2583) (I was searching for "beta", not "OTP"!). It looks like it's possible to setup if you're careful about tagging.

**Comment by alexbakker** [comment]
We have a tag filter that filters out alpha/beta releases for F-Droid, so that they're not automatically picked up by their build system as stable releases. For each release, we'd have to submit a pull request to the ``fdroiddata`` repository to get it listed as an unstable build, and we never did that because review tended to take quite a while.

Looking at it now that situation seems to have improved a bit, so for future alpha or beta releases we'll submit a pull request to get it listed there.

**Comment by alerque** [comment]
Fair enough.
