### ISSUE TITLE
Grouping

### ISSUE THREAD

**Issue by Chaython** [beemdevelopment/Aegis#752]
Instead of having a sandwich[small button in corner, of an otherwise empty header] can you have a horizontal slider of groups [show all groups in a groups header]. Otherwise can you move the group to the sort or as a separate button on the top bar.
It's so awkward and wastefull to just have the groups button on the far right upper third rather than it being with the other buttons etc.

**Comment by alexbakker** [comment]
We'll probably be adding more functionality to the group bottom sheet in the future (for adding an entry to multiple groups in one go, for example), which we would not be able to expose if we were using a slidable header for groups. Also, the reason why the groups button is not incorporated in the action bar, is because we needed a way to indicate that there is currently a group filter active. I agree that the current placement of the groups button makes it look like we're wasting a bit of space though. We're planning to make some changes to the action bar in the future, where hopefully we'll be able to address that.
