### ISSUE TITLE
F-Droid updates are behind play store

### ISSUE THREAD

**Issue by StephanBeer** [beemdevelopment/Aegis#756]
The Aegis F-droid version got updated a day ago, but only to version 1.4.2 as Aegis in the Playstore is the newest 2.0 version. I prefer installing apps via the Fdroid over Playstore but sadly you have to wait so much longer to get the newest app versions or bug fixes ...😐

**Comment by vladut123** [comment]
> The Aegis F-droid version got updated a day ago, but only to version 1.4.2 as Aegis in the Playstore is the newest 2.0 version. I prefer installing apps via the Fdroid over Playstore but sadly you have to wait so much longer to get the newest app versions or bug fixes ...😐

Change the title to F-Droid updates are behind play store

**Comment by alexbakker** [comment]
F-Droid just takes a while to publish new releases. This process is automatic and out of our hands.

**Comment by ctp9** [comment]
I know this issue is closed but I happen to have a question and don't want to open a new issue just to ask a simple question:

Is there any advantage/disadvantage to getting Aegis from F-Droid vs. Play Store and vice versa? Is the app build always exactly the same from either source? And why is Play Store less preferred than F-Droid? Is it due to privacy concerns due to it being a Google product?

Thanks!

**Comment by alexbakker** [comment]
This isn't really the place to discuss Google Play vs F-Droid.

In general: If you're currently not using the Google Play Store at all, I'd recommend getting Aegis from F-Droid. In all other cases, I'd recommend getting Aegis from the Google Play Store.
