### ISSUE TITLE
Can't modify advanced options when adding an entry via scan QCode with v2.0

### ISSUE THREAD

**Issue by zstdadi** [beemdevelopment/Aegis#770]
###### Info

* __Version__: 2.0
* __Source__: GitHub
* __Vault encrypted__: Yes (with biometric unlock)
* __Device__: mobile phone
* __Android version and ROM__: 10.0

###### Steps to reproduce
bug1:
Can't modify advanced options when adding an entry via scan QCode with v2.0, but could modify with v1.4.2, and could modify after add the entry, and could modify when adding an entry via manual input.
I want modify advanced options "time peroid" from 30 to 60.

bug2:
Can't recognize local Qcode picture with v2.0, but could recognize with v1.4.2

###### What do you expect to happen?

Can modify advanced options when adding an entry via scan QCode with v2.0 like v1.4.2
Can recognize local Qcode picture with v2.0 like v1.4.2

**Comment by alexbakker** [comment]
This is by design. Modifying the parameters like that is almost certainly going to result in incorrect codes. Unless the service you're setting up 2FA for supports that somehow, but I've personally never seen that before.

If you really need to change the parameters, you can do so by saving the entry first and then going back to the entry editing screen.
