### ISSUE TITLE
Fingerprint setup turns screen off on Moto G5 Plus

### ISSUE THREAD

**Issue by PopeRigby** [beemdevelopment/Aegis#81]
The MG5+ fingerprint scanner turns off your phone's screen when there isn't a fingerprint prompt. The setup doesn't seem to be giving me a prompt, so my screen just turns off.

**Comment by alexbakker** [comment]
A couple of questions. So, your screen gets turned off when you touch the fingerprint sensor, unless an app is listening for fingerprints? The screen stays on in the settings, but not in the intro? Is MG5+ a custom ROM?

**Comment by PopeRigby** [comment]
MG5+ means Moto G5 Plus. I can't even get past the intro if I'm using a fingerprint to set it up.

**Comment by alexbakker** [comment]
Can you also answer the other questions? What happens if you set Aegis up with a password and try to enable fingerprint later in the settings?

**Comment by flocke** [comment]
I had this behaviour a couple of times as well on my Moto G5 Plus with different apps (I remember it happening during the setup of my WearOS watch) when scanning my fingerprint. It stopped after some update of the ROM I used (don't remember which it was back when this was happening to me) and hasn't happened since. I doubt it is a problem in Aegis. Which ROM are you on?

**Comment by PopeRigby** [comment]
I'm on stock 8.1

**Comment by flocke** [comment]
The last stock version I used was 7.something ... maybe the problem exists there as well...
Do you have "Fingerprint Gestures" under your devices Settings - Moto Actions (I don't know if that even is a thing on stock...). If yes try turning them off.

**Comment by PopeRigby** [comment]
Fingerprint gestures were already off

**Comment by user8446** [comment]
I just downloaded Aegis and have the exact same issue and also have a Moto G5+. It's as if Aegis is not listening for the fingerprint action because the normal action when touching the fingerprint sensor is the same as pressing the power button - to turn the screen on and off, which is what it does on the setup screen.

I got around this by choosing no password at setup and then going back into settings and turning the p/w and the fingerprint toggle back to on.

**Comment by sdellenb** [comment]
FWIW, I have "Single tap" and "Double tap" disabled in the "Fingerprint gestures" menu (Moto G5+ with LineageOS 14.1, "Long tap" does "Screen on/off").
I didn't encounter any issues setting up the fingerprint on the initial Aegis setup.

**Comment by user8446** [comment]
I just checked and those options aren't even available in the stock 8.1. I even have one button nav off.
Weird.

**Comment by vertigo220** [comment]
Not a fix, but should be able to get around this by going into security settings and disabling the option to lock the phone with the fingerprint sensor, completing setup, then turning the option back on.

**Comment by alexbakker** [comment]
Fixed by #240.
