### ISSUE TITLE
Improve Biometric Security

### ISSUE THREAD

**Issue by tunbridgep** [beemdevelopment/Aegis#811]
I've used some other apps where, the first time you run the app after restarting the phone, you must login using your password, not just the fingerprint sensor.

This is important because in some jurisdictions you can be compelled to provide your fingerprint, but not a password.

I understand that the security of a 2fa app is less important than that of a password - more often than not, the device itself is the security - but since this is security focused, I still think it's a good idea.

I also feel personally uncomfortable with someone being able to use just my fingerprint to unlock the device. I'd like the ability to completely disable biometrics entirely if possible.

I propose the following changes:

1. Upon starting the app for the first time after restarting, the first login requires the password
2. When using the lock item in the menu, it will also require the password to log in.
3. Add an option to completely disable biometrics

Also, unrelated, here's a question: if I've NEVER used biometrics for the app, and law enforcement uses the "or login using Biometric security" link, will they then be able to use my fingerprint to log in - a login method I never consented to? That seems like a pretty major security oversight.

Maybe I'm being overly paranoid here.

**Comment by alexbakker** [comment]
> I've used some other apps where, the first time you run the app after restarting the phone, you must login using your password, not just the fingerprint sensor.

Which apps have this feature?

> 1. Upon starting the app for the first time after restarting, the first login requires the password
> 2. When using the lock item in the menu, it will also require the password to log in.

In general, I'm hesitant to introducing security features that can't be enforced at the level of the vault file. Android already asks you to enter your PIN/password after a reboot and that's the correct layer at which to handle that concern in my opinion.

> 3. Add an option to completely disable biometrics

This option already exists. The use of biometrics is opt-in and always will be.

> Also, unrelated, here's a question: if I've NEVER used biometrics for the app, and law enforcement uses the "or login using Biometric security" link, will they then be able to use my fingerprint to log in - a login method I never consented to? That seems like a pretty major security oversight.

If you don't explicitly enable biometric authentication in Aegis, it's impossible to unlock your Aegis vault with biometrics.

**Comment by tunbridgep** [comment]
> Which apps have this feature?

I'm mainly thinking of Keepass2Android and it's "quickunlock", but the phone does it too. That was my main inspiration.

> In general, I'm hesitant to introducing security features that can't be enforced at the level of the vault file. Android already asks you to enter your PIN/password after a reboot and that's the correct layer at which to handle that concern in my opinion.

You're probably right, even if some part of me doesn't feel comfortable with this.

> This option already exists. The use of biometrics is opt-in and always will be

> If you don't explicitly enable biometric authentication in Aegis, it's impossible to unlock your Aegis vault with biometrics.

Ahhh yes, sorry this was my bad. I missed the security option in the settings menu and so thought there was no way to turn it off once active.

**Comment by alexbakker** [comment]
> I'm mainly thinking of Keepass2Android and it's "quickunlock", but the phone does it too. That was my main inspiration. This way, even if someone gets access to your phone, you're still protected.

I see. So this actually works a bit differently than your initial description. Instead of asking for your password after a reboot, Keepass2Android asks for it after the app has been restarted. The intent is also different. After a restart, Keepass2Android doesn't ask for a password for security reasons, but out of necessity, because it cannot decrypt the database with biometrics in this configuration.

> Also keep in mind that if the Android fingerprint security ever gets compromised, it potentially risks your entire database, even if all they have access to is the file

Our assumption is that only users who trust Android's biometric authentication will turn on biometric authentication.

> (my understanding is that the database password is encrypted with biometrics somewhere in an Android security database).

This is incorrect. Aegis does not store your password anywhere, encrypted or otherwise.

> This sort of "decrypt database with password, decrypt in-memory version with fingerprint" effectively prevents that, as it would require a memory dump.

> I feel this is why KP2A does it that way. Of course it also has to maintain compatibility with other KeePass programs, so that would have likely also been considered.

I took a quick look at their source code, and it appears to me that this is actually not how it works in Keepass2Android at all. Keepass2Android has 2 modes for biometric unlock:

1. **Full Biometric Unlock**. In this mode, Keepass2Android takes your password, encrypts it with an Android KeyStore key and writes it to a preference file. The next time you open the app, it asks you for biometric authentication to allow use of the Android KeyStore key, decrypts the password and finally decrypts the database.

    This is somewhat similar to the way Aegis works, with the main difference being that we don't have to store an encrypted password, just the encrypted master key.

2. **Biometric Unlock for QuickUnlock**. This is the one you'd like to see in Aegis. In this mode, Keepass2Android takes the literal string "QuickUnlock", encrypts it with an Android KeyStore key and writes it to a preference file. See: https://github.com/PhilippC/keepass2android/blob/05f8a067f1518861238fd0a3cd9b794459774d49/src/keepass2android/FingerprintSetupActivity.cs#L184-L190. The next time you open the app, it asks you for biometric authentication and tries to decrypt the encrypted "QuickLock" string. If decryption succeeds, it will just set ``quickLocked = false`` and show the database contents. Note that there was no decryption of the database here, because it is still present in memory (as well as the password, for some reason).

Are you sure you're still a fan of "Quick Unlock"?

> That's putting a lot of eggs in the Android basket.

You think so? I think we can trust Android to ask for your PIN/password instead of biometrics after a reboot. I can't think of any ways to mess that up. We have to trust Android with a lot more than just that.

**Comment by alexbakker** [comment]
In conclusion, I don't think implementing this in Aegis would meaningfully increase security.

**Comment by tunbridgep** [comment]
Wow that was quite the write up.

I guess you're right about this. I should have done further reading on the
topic before suggesting
