### ISSUE TITLE
Importing from Google Authenticator

### ISSUE THREAD

**Issue by Txatxiquesi** [beemdevelopment/Aegis#82]
Hello, i have a error when i try to import data from my google authenticator, root permisions  & file access already granted, the error is:
"_A error acurred while trying to parse the file:  android.databse.sqlite.SQLITEexception: no such table: account( code 1 SQLITE_ERROR):, while compiling: SELECT*FROM accounts_"

**Comment by michaelschattgen** [comment]
Thanks for your contribution. Did you use Titanium Backup or something similar in the past?

**Comment by Txatxiquesi** [comment]
> Thanks for your contribution. Did you use Titanium Backup or something similar in the past?

You are right, i restore a backup of the google authenticator done with 3c tools.

**Comment by alexbakker** [comment]
It appears that there are 2 more files that we need to copy over when importing from Google Authenticator, ``databases-shm`` and ``databases-wal``.

**Comment by MPeti1** [comment]
@michaelschattgen sorry for not replying, didn't notice the reply. Yeah I used that, not for Aegis but maybe for Google Auth

**Comment by LucaDLL** [comment]
I have this problem too, any idea on how to fix or an ETA for a fix? Thanks and congratulations on your work.

**Comment by MPeti1** [comment]
@LucaDLL if I remember correctly a fix is already there in the master branch, it just need to be released. (Or that was the steam bug?) Maybe currently it has problems and that's why they didn't release it, but in the meantime you can build it yourself and install that version with Android Studio.

An other method could be if you open the database file* with a db explorer app (for example MiXplorer has such a component), you can read the secret yourself. You just need to copy or write that into the secret field for a new profile in Aegis. Be careful with copy pasting though, any app on your phone can subscribe for clipboard change events!

*You can file the db here: /data/data/com.google.android.apps.authenticator2/databases/databases

**Comment by alexbakker** [comment]
@LucaDDL There is no fix for this yet, but I think including those 2 files I mentioned in [a previous comment](https://github.com/beemdevelopment/Aegis/issues/82#issuecomment-496027370) would work.

We don't do ETA's, so I can't tell you when a fix for this will land. Consider submitting a patch if you would like to see this fixed sooner rather than later.

**Comment by MPeti1** [comment]
@alexbakker I think also databases-journal could be needed. I don't have -shm nor -wal besides the databases file, but I have a -journal one.

But still, if I only copy over the `databases` file to an other directory, I can still browse it with MiXplorer's SQLite editor and see the accounts table with its data, and Aegis gives me the same error as in the issue

**Comment by ildar** [comment]
It looks like the `Google Authenticator(2)`'s file import should work but it doesn't.
I use the very old version 2.21 from [F-Droid Archive](https://f-droid.org/archive/com.google.android.apps.authenticator2_21.apk) and crashes:
```06-21 13:56:49.239 29533 29533 E AndroidRuntime: FATAL EXCEPTION: main
06-21 13:56:49.239 29533 29533 E AndroidRuntime: Process: com.beemdevelopment.aegis, PID: 29533
06-21 13:56:49.239 29533 29533 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.beemdevelopment.aegis/com.beemdevelopment.aegis.ui.ImportEntriesActivity}: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
06-21 13:56:49.239 29533 29533 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4129)
...
06-21 13:56:49.239 29533 29533 E AndroidRuntime: Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
06-21 13:56:49.239 29533 29533 E AndroidRuntime: 	at com.beemdevelopment.aegis.importers.SqlImporterHelper.read(SourceFile:21)
06-21 13:56:49.239 29533 29533 E AndroidRuntime: 	at com.beemdevelopment.aegis.importers.SqlImporterHelper.read(SourceFile:5)
06-21 13:56:49.239 29533 29533 E AndroidRuntime: 	at com.beemdevelopment.aegis.importers.GoogleAuthImporter.read(SourceFile:4)
```

The database file is fine, I checked with `sqlite3 database .dump`
