### ISSUE TITLE
Unsupported protocol: https while scanning QR code

### ISSUE THREAD

**Issue by Lineflyer** [beemdevelopment/Aegis#837]
###### Info

* __Version__: 2.0.2
* __Source__: Google Play
* __Vault encrypted__: Yes (with biometric unlock)
* __Device__: Samsung Galaxy S20
* __Android version and ROM__: Android 11, Stock ROM

###### Steps to reproduce

I tried to setup 2FA for my [Synology](https://www.synology.com) account.
According to their website they support "standard 2FA" and also refer to using the Google Authenticator app is compatible.
I followed the process and was asked to scan the shown QR-code to enable my OTP generation.

###### What do you expect to happen?
The QR-code should be scanned and accepted.

###### What happens instead?
Aegis reports (after the localized generic error message):
```com.beemdevelopment.aegis.otp.GoogleAuthInfoException: Unsupported protocol: https```

Not sure if Synology does something wrong here, however the error looks suspicious. 
Why should https be unsupported.

###### Log

Tell me if needed and how to retrieve, I will provide.

**Comment by alexbakker** [comment]
Sounds like you're not scanning the correct QR code. Are you scanning a QR code that contains a regular link, perhaps? EA Origin does something similarly confusing, where they first show a QR code with a link to the Google Playstore, and then on the next screen they show the QR code that you should actually scan with your authenticator app.

> Why should https be unsupported.

Because OTP URI's start with ``otpauth://``, not ``https://``.

**Comment by Lineflyer** [comment]
I will check back on that page.

Could be, but the text above stated to scan this QR to add the OTP. However, will check and report back.

**Comment by Lineflyer** [comment]
Follow up as promised:
You are perfectly right. The website was linking to some 2FA app but said to scan the code to enable the 2FA process. It was quite misunderstand-able. But just hitting "Next" finally brought up the right QR code for 2FA.
