### ISSUE TITLE
Delete password field when user types wrong password

### ISSUE THREAD

**Issue by Jonas1312** [beemdevelopment/Aegis#85]
Every time I enter a wrong password I have to:
1) click the unlock button
2) close the "couldn't unlock vault" window
3) delete every character in the password field
4) retype password

It's a bit annoying, maybe we could auto-delete the wrong password and bypass the "couldn't ..." window by showing a message above or under the password field.

**Comment by michaelschattgen** [comment]
I like this suggestion, thanks!

Although it would be a bit annoying if you know you just mistyped the last character and need to type the whole password again. What do you think @alexbakker?

**Comment by alexbakker** [comment]
I like this idea, but I agree that clearing the password field might be annoying. I have a variation that might improve the UX a bit more. Instead of clearing the password, how about we automatically bring the keyboard back up and preselect all characters in the password field, so that clearing it is one tap away?

**Comment by Jonas1312** [comment]
Adding an erase button directly in the password field could be a solution too

![nMAJn](https://user-images.githubusercontent.com/15847892/57782638-f38ed000-772c-11e9-9d48-9a95d05643aa.png)
