### ISSUE TITLE
Add an option to make biometric a default  option even if i click "password"

### ISSUE THREAD

**Issue by elieobeid7** [beemdevelopment/Aegis#877]
Those two proposals were  made

https://github.com/beemdevelopment/Aegis/issues/839
https://github.com/beemdevelopment/Aegis/issues/859

and the answer

`You're probably seeing the password reminder. Try entering your password once. After that, Aegis should start prompting biometrics by default again.`

And that's true, but I hit "use password" multiple times by mistake, anyone who has a big thumb can hit the "use password" by mistake, it's a pain to keep fetching the password every time someone pick that option by mistake.  It'd be awesome to add a default biometric option, so that if you switch to password and switch back to biometric, it saves the biometric.

So I think a better behaviour would be to save the last option you used to sign in always and use that a default, because if a user picks password then switches back to biometric, it means that he picked password by mistake, and he really wants to use biometric instead

**Comment by alexbakker** [comment]
I don't really understand what you're requesting here. The whole point of the password reminder is to gently force the user to enter their password every once in a while, so that they 1. are sure they still remember their password and 2. get reminded that their password is the primary way to get into their vault in case biometrics break.

There's an option to disable the password reminder, but we really don't recommend using that.

> I hit "use password" multiple times by mistake

There is no "use password" button.

**Comment by elieobeid7** [comment]
Ah, you got a good point, in fact, the reason I moved away from authenticator plus is that I forgot the master password and the developer abandoned it anyway, that's when I found Aegis.

So it's a good idea to gently force the user to keep using his password. Few months ago my friend was logged out of Authy and couldn't sign in because he forgot the password and told him to use Aegis as well.

So ok I totally agree with your decision and I'm going to close my ticket as a result.
