### ISSUE TITLE
Support for Okta verify

### ISSUE THREAD

**Issue by bserem** [beemdevelopment/Aegis#887]
Okta verify is a 2FA used by companies a lot, they do provide mobile apps but they are very limited (probably intentional) so one can't actually backup their information or transfer them easily to another device.

I tried scanning an Okta QR with Aegis but I get the error `Parameter 'secret' is not present`.
Is it possible to provide Okta support in Aegis?

Thanks

**Comment by alexbakker** [comment]
How can I obtain an Okta QR to test with?

Also, are you sure there's no option to use a regular TOTP app when setting up 2FA with Okta?

**Comment by bserem** [comment]
I suppose you can start here: https://www.okta.com/free-trial/

For all I've seen, no TOTP option available. If I loose Okta then I need to contact support (which would actually be weird since I won't be able to access the company email either...) for it to be reset, no alternative provided.
I am the end user in this situation, so the info I can provide is a bit limited.

**Comment by krisu5** [comment]
Someone has requested for Okta icon on aegis-icons on last september (aegis-icons/aegis-icons#376). So there is some way to add it to Aegis, I found this tutorial for example: https://yingtongli.me/blog/2018/07/19/okta.html

**Comment by alexbakker** [comment]
I created a trial Okta account and tried scanning the QR code with their Okta Verify app. It failed, probably because the internet connection was turned off on that device. This makes me think their proprietary protocol requires an internet connection in order to function. Aegis doesn't request the internet permission and we'd like to keep it that way.

> I found this tutorial for example: https://yingtongli.me/blog/2018/07/19/okta.html

I tried the "Can't scan" route as well, but it seems like it has changed since that article was written. I now get asked for an email address so that they can send an activation link to the device I have Okta Verify installed on.

**Comment by krisu5** [comment]
> This makes me think their proprietary protocol requires an internet connection in order to function. Aegis doesn't request the internet permission and we'd like to keep it that way.

If that's the case, I have to remove that icon from the pack too, if solution hasn't found. I ask the OP of the icon issue about how they got the 2FA work.

**Comment by krisu5** [comment]
Here's what I got as answer:

> The method you linked does work but it might depend on your company's Okta policy. It's also possible Okta has removed that option to get more people to use their app.
> 
> Here's what I did a few months ago to get it to work: First use Okta Verify to create the initial account, then you can go to your account settings and register a normal 2FA app and remove Okta Verify.

I guess answer is *"it depends"* ¯\\\_(ツ)_/¯

**Comment by bserem** [comment]
Yup, no luck for some of us then, but it was worth trying. Thanks!

I guess we can close this?

**Comment by ulidtko** [comment]
Hey @bserem I just want to mention that this issue isn't rare... I got it too.

This blog https://yingtongli.me/blog/2018/07/19/okta.html — was super helpful! :tada: With info there, I got my Okta 2fa into Aegis.

Perhaps it's worthwhile to backup that guide, document it within Aegis or something. Because linkrot happens.

**Comment by bserem** [comment]
@ulidtko this is great info! It worked without any issues.

Thanks
