### ISSUE TITLE
Pill-based group selection

### ISSUE THREAD

**Issue by k3davis** [beemdevelopment/Aegis#914]
When you put at least one record into a group, the pill-shaped "Groups" filter appears in the upper-right corner. I obviously don't have any context for how many groups people typically make, but for a low number of groups, would you consider creating a pill-shaped button for each group, and only grouping into the singular "groups" filter if there are more than a couple/the length exceeds the device screen width (if there is a responsive option like that, I'm not an Android developer)? I would think you could keep this regardless of the number of groups so long as the list could scroll horizontally.

Because I only have two groups, I'd prefer to toggle them on/off from dedicated buttons instead of clicking the groups filter button, choosing the filter I want, and clicking Save (1 action instead of 3).

Thanks for consideration!

**Comment by k3davis** [comment]
A (very) crude mockup of the idea, in case it is useful
![mockup](https://user-images.githubusercontent.com/1307914/168074002-8585615c-9762-4d1e-8786-16730a4ed6a1.png)
.

**Comment by Doge7734** [comment]
As another user who, despite only having two TOTP codes since I don't have too many accounts (or the ones I do have are too important and so I use a YubiKey with WebAuthn) , uses Aegis, I think that looks good and would be useful.

**Comment by tiniwings** [comment]
Just checking, if this feature can be considered. It will be easy to access if we have more entries.

**Comment by michaelschattgen** [comment]
I've been actually testing something like this earlier this week. We're still unsure about the progressbar above it since it looks a bit off now, but we're definitely considering this approach.


https://github.com/user-attachments/assets/c9ecc10b-97fe-4c80-8073-201bae993ae6

**Comment by bazzik** [comment]
A question (maybe somebody can tell if it's possible to have it this way) -- is it possible to have the groups working as a 1-tap switch rather than a selection (so only 1 can be selected with a single tap)?

I mean: lets say I have 3 groups: Personal, Work 1, Work 2. I would like to have it working in a way that allows to quickly switch between them (1 tap ideally) rather than: tap on a desired one to select it, now top on previously active that is no longer needed, tap on Save...
