### ISSUE TITLE
'Unsupported protocol: null​​' on Gaijin.net (gaming service)

### ISSUE THREAD

**Issue by justingoldberg** [beemdevelopment/Aegis#932]
###### Info

* __Version__: 2.0.2
* __Source__: (Google Play/GitHub/F-Droid/?) Google Play
* __Vault encrypted__: Yes (with biometric unlock)/Yes/No: Yes with biometric unlock
* __Device__: LG K51
* __Android version and ROM__: 

###### Steps to reproduce

Signup on gaijin.
Go to enable 2fa, then scan the QR image into Aegis. I get this error:
​com.beemdevelopment.aegis.otp.GoogleAuthInfoException: Unsupported protocol: null​​

###### What do you expect to happen?

...

###### What happens instead?

...

###### Log

```
If applicable, paste the debug log here.
```

**Comment by alexbakker** [comment]
Do you have an example QR code I can test with by any chance? (Make sure it's not valid for your actual account). I'm unable to register and enable 2FA on that website, because it requires me to enter my phone number.

Either way, if this is not HOTP or TOTP, I don't think it's likely we'll add support specifically for Gaijin.net.

**Comment by alexbakker** [comment]
I guess someone else already opened it: "Sorry! File not found." Could you send a new link to beemdevelopment@gmail.com?

**Comment by alexbakker** [comment]
No response.

I suspect that Gaijin doesn't support TOTP. Feel free to reopen if you still suspect that this is a bug in Aegis.
