### ISSUE TITLE
Biometrics works with 1 fingerprint, fails with 2 and more

### ISSUE THREAD

**Issue by perfiction** [beemdevelopment/Aegis#941]
###### Info

* __Version__: 2.0.3
* __Source__: F-Droid
* __Vault encrypted__: Yes
* __Device__: Xiaomi Redmi Note 4 (mido)
* __Android version and ROM__: PixelExperience 12.1

###### Steps to reproduce

- Enroll one fingerprint in device settings
- Succesfully enable the biometrics in Aegis settings
- Add another fingerprint in device settings
- Try to disable and re-enable biometrics in Aegis settings

###### What do you expect to happen?

Biometrics configured succesfully

###### What happens instead?

Biometrics configuration fails with a popup error "Some devices have poor implementation of Biometrics unlock, your may be one of them." and an exception:
```
com.beemdevelopment.aegis.vault.slots.SlotException
javax.crypto.AEADBadTagException
```

###### Log

[log.txt](https://github.com/beemdevelopment/Aegis/files/9127240/log.txt)

Issue similar to #889 but it happens only when more than one fingerprint is added + the exception is different. Other apps using biometeric (for example banking app, Magisk Manager, Simple Gallery) have no issues during configuration.

I recently updated my phone from Android 11 to 12 (both were PixelExperience ROMs), in 11 Aegis worked flawlessly. If it's ROM-specific issue are there any suggestions I could forward to the maintainer to hopefully get the issue fixed?

**Comment by perfiction** [comment]
I believe it's a ROM issue after all, similar problem happens with KeePassDX fingerprint configuration. I've tried LineageOS and it works fine.

**Comment by perfiction** [comment]
I believe it's a ROM issue after all, similar problem happens with KeePassDX fingerprint configuration. I've tried LineageOS and it works fine.

**Comment by steponmepls** [comment]
I'm experiencing the same problem except that it works and then stops working on the very same [ROM](https://forum.xda-developers.com/t/android-13-lineageos-20-mido-vanilla-by-zeelog-stable-no-bugs-smooth.4516771/) install. I did try to do multiple clean installs just to make sure since and at first I can import my vault just fine + toggling off and on the biometric feature but after uninstalling the app and doing everything from scratch it stops working displaying the usual error.

What I did was:

1. Download the apk from github after a clean ROM install
2. Import the vault from a file
3. Enter my password for decryption
4. Toggle off biometric (probably on by default from the exported vault settings)
5. Toggle the option back on
6. Proceed to enable biometric settings for other apps (ex: BitWarden which works just fine)
7. Uninstall Aegis and reinstall from Play Store
8. Repeat steps from 2 to 6
9. `AEADBadTagException` error happens

I did experience this error with only one finger option added to my biometric configs so I don't think the amount of entries matters. I also tried disabling biometric from other apps but without results.
