### ISSUE TITLE
Export encrypted Zip file

### ISSUE THREAD

**Issue by MarvinHannott** [beemdevelopment/Aegis#965]
This would be a convenient way for decrypting a backup by hand without sacrificing security. This would be handy for retrieving a specific security code or to manipulate the backup so it can be imported by another application.

**Comment by alexbakker** [comment]
I'm not sure I'd be in favor. The way encryption is done for .ZIP files is... not great. Even with the AES option, the static number of iterations of 1000 used for PBKDF2 is very low.

Either way, if we add support for this, there would be a couple of limitations:

1. We'd use AES instead of ZipCrypto. This means that some applications won't be able to decrypt and extract the ZIP files that Aegis produces. Windows File Explorer is one example of such an application.
2. The option to produce a .ZIP file will only be available when exporting and a password will have to be entered manually every time. Aegis doesn't store the user's password anywhere, so this wouldn't work for automatic backups.

**Comment by MarvinHannott** [comment]
Mh, I see your point. And I think other file formats like 7z aren't any better. 

Though, that got me thinking: What about JSON Web Encryption and asymmetric encryption? I mean, it's perfectly fine to store a public key on the phone, while the private key sits securely on my machine. And using an open encryption scheme would make it much simpler for third party software to decrypt.

In the end, doing it manually absolutely works for me, if you think it isn't worth the headache.

**Comment by alexbakker** [comment]
I'm starting to sound like a downer, but I'm also not a super big fan of the JOSE family of standards. Either way, you'd still need a way to actually decrypt that file, preferably without having to write a command line tool yourself first

If [age](https://github.com/C2SP/C2SP/blob/main/age.md) existed at the time we started working on Aegis, we would have probably used that. I think it could fully replace our custom vault format (if we write a custom recipient for Android Keystore keys), because it has support for symmetric recipients (passwords) and asymmetric recipients. Something to consider for the future perhaps.

**Comment by alexbakker** [comment]
To summarize, I don't think we'll be adding support for exporting encrypted ZIP files. If we decide to switch to a different vault format in the future, I think we should consider using [age](https://github.com/C2SP/C2SP/blob/main/age.md) so that the contents are easier to decrypt using off-the-shelf tools.
